// CEL conformance tests ported from google/cel-spec
// https://github.com/google/cel-spec/tree/master/tests/simple/testdata
import { describe, it } from 'node:test'
import { assertCel, assertCelError, cel } from './helpers.js'

// ============================================================================
// basic.textproto
// ============================================================================
describe('basic', () => {
  describe('self_eval_zeroish', () => {
    it('self_eval_int_zero', () => assertCel('0', 0n))
    it('self_eval_uint_zero', () => assertCel('0u', 0n))
    it('self_eval_uint_alias_zero', () => assertCel('0U', 0n))
    it('self_eval_float_zero', () => assertCel('0.0', 0.0))
    it('self_eval_float_zerowithexp', () => assertCel('0e+0', 0.0))
    it('self_eval_string_empty', () => assertCel("''", ''))
    it('self_eval_string_empty_quotes', () => assertCel('""', ''))
    it('self_eval_string_raw_prefix', () => assertCel('r""', ''))
    it('self_eval_bytes_empty', () => assertCel('b""', new Uint8Array([])))
    it('self_eval_bool_false', () => assertCel('false', false))
    it('self_eval_null', () => assertCel('null', null))
    it('self_eval_empty_list', () => assertCel('[]', []))
    it('self_eval_empty_map', () => assertCel('{}', new Map()))
    it('self_eval_string_raw_prefix_triple_double', () => assertCel('r""""""', ''))
    it('self_eval_string_raw_prefix_triple_single', () => assertCel("r''''''", ''))
  })

  describe('self_eval_nonzeroish', () => {
    it('self_eval_int_nonzero', () => assertCel('42', 42n))
    it('self_eval_uint_nonzero', () => assertCel('123456789u', 123456789n))
    it('self_eval_uint_alias_nonzero', () => assertCel('123456789U', 123456789n))
    it('self_eval_int_negative_min', () => assertCel('-9223372036854775808', -9223372036854775808n))
    it('self_eval_float_negative_exp', () => assertCel('-2.3e+1', -23.0))
    it('self_eval_string_excl', () => assertCel('"!"', '!'))
    it('self_eval_string_escape', () => assertCel("'\\''", "'"))
    it.skip('self_eval_bytes_escape', () => {})
    it.skip('self_eval_bytes_invalid_utf8', () => {})
    it('self_eval_list_singleitem', () => assertCel('[-1]', [-1n]))
    it('self_eval_map_singleitem', () => assertCel('{"k":"v"}', new Map([['k', 'v']])))
    it('self_eval_bool_true', () => assertCel('true', true))
    it('self_eval_int_hex', () => assertCel('0x55555555', 1431655765n))
    it('self_eval_int_hex_negative', () => assertCel('-0x55555555', -1431655765n))
    it('self_eval_uint_hex', () => assertCel('0x55555555u', 1431655765n))
    it('self_eval_uint_alias_hex', () => assertCel('0x55555555U', 1431655765n))
    it('self_eval_unicode_escape_four', () => assertCel('"\\u270c"', '\u270c'))
    it('self_eval_unicode_escape_eight', () => assertCel('"\\U0001f431"', '\u{1f431}'))
    it('self_eval_ascii_escape_seq', () => assertCel(String.raw`"\a\b\f\n\r\t\v\"\'\\"`  , '\x07\b\f\n\r\t\x0b"\'\\'))
  })

  describe('variables', () => {
    it('self_eval_bound_lookup', () => assertCel('x', 123n, { x: 123n }))
    it.skip('self_eval_unbound_lookup - returns undefined instead of error', () => assertCelError('x'))
    it.skip('unbound_is_runtime_error', () => {
      // x || true with unbound x - requires error short-circuit
    })
  })

  describe('functions', () => {
    it('binop', () => assertCel('1 + 1', 2n))
    it('unbound', () => assertCelError('f_unknown(17)'))
    it.skip('unbound_is_runtime_error', () => {
      // f_unknown(17) || true - requires error short-circuit
    })
  })

  describe('reserved_const', () => {
    it('false', () => assertCel('false', false))
    it('true', () => assertCel('true', true))
    it('null', () => assertCel('null', null))
  })
})

// ============================================================================
// comparisons.textproto
// ============================================================================
describe('comparisons', () => {
  describe('eq_literal', () => {
    it('eq_int', () => assertCel('1 == 1', true))
    it('not_eq_int', () => assertCel('-1 == 1', false))
    it('eq_int_uint', () => assertCel('dyn(1) == 1u', true))
    it('not_eq_int_uint', () => assertCel('dyn(2) == 1u', false))
    it('eq_int_double', () => assertCel('dyn(1) == 1.0', true))
    it('not_eq_int_double', () => assertCel('dyn(2) == 1.0', false))
    it('eq_uint', () => assertCel('2u == 2u', true))
    it('not_eq_uint', () => assertCel('1u == 2u', false))
    it('eq_uint_int', () => assertCel('dyn(1u) == 1', true))
    it('not_eq_uint_int', () => assertCel('dyn(2u) == 1', false))
    it('eq_uint_double', () => assertCel('dyn(1u) == 1.0', true))
    it('not_eq_uint_double', () => assertCel('dyn(2u) == 1.0', false))
    it('eq_double', () => assertCel('1.0 == 1.0e+0', true))
    it('not_eq_double', () => assertCel('-1.0 == 1.0', false))
    it('not_eq_double_nan', () => assertCel('0.0/0.0 == 0.0/0.0', false))
    it('not_eq_int_double_nan', () => assertCel('dyn(1) == 0.0/0.0', false))
    it('not_eq_uint_double_nan', () => assertCel('dyn(1u) == 0.0/0.0', false))
    it('eq_double_int', () => assertCel('dyn(1.0) == 1', true))
    it('not_eq_double_int', () => assertCel('dyn(2.0) == 1', false))
    it('eq_double_uint', () => assertCel('dyn(1.0) == 1u', true))
    it('not_eq_double_uint', () => assertCel('dyn(2.0) == 1u', false))
    it('eq_string', () => assertCel("'' == \"\"", true))
    it('not_eq_string', () => assertCel("'a' == 'b'", false))
    it('eq_raw_string', () => assertCel("'abc' == r'abc'", true))
    it('not_eq_string_case', () => assertCel("'abc' == 'ABC'", false))
    it('eq_string_unicode', () => assertCel("'\u03AF\u03C3\u03BF\u03C2' == '\u03AF\u03C3\u03BF\u03C2'", true))
    it('not_eq_string_unicode_ascii', () => assertCel("'a' == '\u00E0'", false))
    it('no_string_normalization', () => assertCel("'Am\\u00E9lie' == 'Ame\\u0301lie'", false))
    it('eq_null', () => assertCel('null == null', true))
    it('eq_bool', () => assertCel('true == true', true))
    it('not_eq_bool', () => assertCel('false == true', false))
    it.skip('eq_bytes', () => assertCel("b'\u00ff' == b'\\303\\277'", true))
    it('not_eq_bytes', () => assertCel("b'abc' == b'abcd'", false))
    it('eq_list_empty', () => assertCel('[] == []', true))
    it('eq_list_null', () => assertCel('[null] == [null]', true))
    it('not_eq_list_null', () => assertCel("['1', '2', null] == ['1', '2', '3']", false))
    it('eq_list_numbers', () => assertCel('[1, 2, 3] == [1, 2, 3]', true))
    it.skip('eq_list_mixed_type_numbers', () => assertCel('[1.0, 2.0, 3] == [1u, 2, 3u]', true))
    it.skip('not_eq_list_mixed_type_numbers', () => assertCel('[1.0, 2.1] == [1u, 2]', false))
    it('not_eq_list_order', () => assertCel('[1, 2, 3] == [1, 3, 2]', false))
    it('not_eq_list_string_case', () => assertCel("['case'] == ['cAse']", false))
    it.skip('not_eq_list_length', () => assertCel("['one'] == [2, 3]", false))
    it('not_eq_list_false_vs_types', () => assertCel("[1, 'dos', 3] == [1, 2, 4]", false))
    it('eq_map_empty', () => assertCel('{} == {}', true))
    it('eq_map_null', () => assertCel("{'k': null} == {'k': null}", true))
    it('not_eq_map_null', () => assertCel("{'k': 1, 'j': 2} == {'k': 1, 'j': null}", false))
    it('eq_map_onekey', () => assertCel("{'k':'v'} == {\"k\":\"v\"}", true))
    it('eq_map_double_value', () => assertCel("{'k':1.0} == {'k':1e+0}", true))
    it.skip('eq_map_mixed_type_numbers', () => assertCel('{1: 1.0, 2u: 3u} == {1u: 1, 2: 3.0}', true))
    it('not_eq_map_value', () => assertCel("{'k':'v'} == {'k':'v1'}", false))
    it('not_eq_map_extra_key', () => assertCel("{'k':'v','k1':'v1'} == {'k':'v'}", false))
    it('eq_map_key_order', () => assertCel("{'k1':'v1','k2':'v2'} == {'k2':'v2','k1':'v1'}", true))
    it('not_eq_map_key_casing', () => assertCel("{'key':'value'} == {'Key':'value'}", false))
    it('not_eq_map_false_vs_types', () => assertCel("{'k1': 1, 'k2': 'dos', 'k3': 3} == {'k1': 1, 'k2': 2, 'k3': 4}", false))
    it.skip('eq_mixed_types', () => assertCel('1.0 == 1', true))
    it.skip('eq_list_elem_mixed_types', () => assertCel('[1] == [1.0]', true))
    it('eq_map_value_mixed_types', () => assertCel("{'k':'v', 1:1} == {'k':'v', 1:'v1'}", false))
    it.skip('eq_dyn_json_null - proto', () => {})
    it('not_eq_dyn_bool_null', () => assertCel('dyn(false) == null', false))
    it('not_eq_dyn_bytes_null', () => assertCel("dyn(b'') == null", false))
    it('not_eq_dyn_double_null', () => assertCel('dyn(2.1) == null', false))
    it('not_eq_dyn_duration_null', () => assertCel("dyn(duration('0s')) == null", false))
    it('not_eq_dyn_int_null', () => assertCel('dyn(1) == null', false))
    it('not_eq_dyn_list_null', () => assertCel('dyn([]) == null', false))
    it('not_eq_dyn_map_null', () => assertCel('dyn({}) == null', false))
    it.skip('not_eq_dyn_proto2_msg_null - proto', () => {})
    it.skip('not_eq_dyn_proto3_msg_null - proto', () => {})
    it('not_eq_dyn_string_null', () => assertCel("dyn('') == null", false))
    it('not_eq_dyn_timestamp_null', () => assertCel('dyn(timestamp(0)) == null', false))
    it('not_eq_list_elem_null', () => assertCel('[1, 2, null] == [1, null, 3]', false))
    it('not_eq_map_value_null', () => assertCel("{1:'hello', 2:'world'} == {1:'goodbye', 2:null}", false))
    it('eq_dyn_int_uint', () => assertCel('dyn(1) == 1u', true))
    it('eq_dyn_int_double', () => assertCel('dyn(1) == 1.0', true))
    it('eq_dyn_uint_int', () => assertCel('dyn(1u) == 1', true))
    it('eq_dyn_uint_double', () => assertCel('dyn(1u) == 1.0', true))
    it('eq_dyn_double_int', () => assertCel('dyn(1.0) == 1', true))
    it('eq_dyn_double_uint', () => assertCel('dyn(1.0) == 1u', true))
    it('not_eq_dyn_int_uint', () => assertCel('dyn(1) == 2u', false))
    it('not_eq_dyn_int_double', () => assertCel('dyn(1) == 2.0', false))
    it('not_eq_dyn_uint_int', () => assertCel('dyn(1u) == 2', false))
    it('not_eq_dyn_uint_double', () => assertCel('dyn(1u) == 120', false))
    it('not_eq_dyn_double_int', () => assertCel('dyn(1.0) == 2', false))
    it('not_eq_dyn_double_uint', () => assertCel('dyn(1.0) == 2u', false))
  })

  // Skip eq_wrapper section entirely - proto wrapper types
  describe('eq_wrapper', () => {
    it.skip('eq_wrapper tests - proto wrapper types not supported', () => {})
  })

  describe('ne_literal', () => {
    it('ne_int', () => assertCel('24 != 42', true))
    it('not_ne_int', () => assertCel('1 != 1', false))
    it('ne_int_double', () => assertCel('dyn(24) != 24.1', true))
    it('not_ne_int_double', () => assertCel('dyn(1) != 1.0', false))
    it('ne_int_uint', () => assertCel('dyn(24) != 42u', true))
    it('not_ne_int_uint', () => assertCel('dyn(1) != 1u', false))
    it('ne_uint', () => assertCel('1u != 2u', true))
    it('not_ne_uint', () => assertCel('99u != 99u', false))
    it('ne_uint_double', () => assertCel('dyn(1u) != 2.0', true))
    it('not_ne_uint_double', () => assertCel('dyn(99u) != 99.0', false))
    it('ne_double', () => assertCel('9.0e+3 != 9001.0', true))
    it('not_ne_double_nan', () => assertCel('0.0/0.0 != 0.0/0.0', true))
    it('not_ne_int_double_nan', () => assertCel('dyn(1) != 0.0/0.0', true))
    it('not_ne_uint_double_nan', () => assertCel('dyn(1u) != 0.0/0.0', true))
    it('not_ne_double', () => assertCel('1.0 != 1e+0', false))
    it('ne_double_int', () => assertCel('dyn(9000) != 9001.0', true))
    it('not_ne_double_int', () => assertCel('dyn(1) != 1e+0', false))
    it('ne_double_uint', () => assertCel('dyn(9000u) != 9001.0', true))
    it('not_ne_double_uint', () => assertCel('dyn(1u) != 1e+0', false))
    it('ne_double_nan', () => assertCel('0.0/0.0 != 0.0/0.0', true))
    it('ne_string', () => assertCel("'abc' != ''", true))
    it('not_ne_string', () => assertCel("'abc' != 'abc'", false))
    it('ne_string_unicode', () => assertCel("'r\u00e9sum\u00e9' != 'resume'", true))
    it('not_ne_string_unicode', () => assertCel("'\u03AF\u03B4\u03B9\u03BF' != '\u03AF\u03B4\u03B9\u03BF'", false))
    it.skip('ne_bytes', () => assertCel("b'\\x00\\xFF' != b'\u00ff'", true))
    it.skip('not_ne_bytes', () => assertCel("b'\\303\\277' != b'\u00ff'", false))
    it('ne_bool', () => assertCel('false != true', true))
    it('not_ne_bool', () => assertCel('true != true', false))
    it('not_ne_null', () => assertCel('null != null', false))
    it('ne_list_empty', () => assertCel('[] != [1]', true))
    it('not_ne_list_empty', () => assertCel('[] != []', false))
    it('ne_list_bool', () => assertCel('[true, false, true] != [true, true, false]', true))
    it('not_ne_list_bool', () => assertCel('[false, true] != [false, true]', false))
    it('not_ne_list_of_list', () => assertCel('[[]] != [[]]', false))
    it('ne_map_by_value', () => assertCel("{'k':'v'} != {'k':'v1'}", true))
    it('ne_map_by_key', () => assertCel("{'k':true} != {'k1':true}", true))
    it('not_ne_map_int_to_float', () => assertCel('{1:1.0} != {1:1.0}', false))
    it('not_ne_map_key_order', () => assertCel("{'a':'b','c':'d'} != {'c':'d','a':'b'}", false))
    it.skip('ne_mixed_types', () => assertCel('2u != 2', false))
    it.skip('ne_proto2 - proto', () => {})
    it.skip('ne_proto3 - proto', () => {})
    it.skip('ne_proto2_missing_fields_neq - proto', () => {})
    it.skip('ne_proto3_missing_fields_neq - proto', () => {})
    it.skip('ne_proto_nan_not_equal - proto', () => {})
    it.skip('ne_proto_different_types - proto', () => {})
    it.skip('ne_proto2_any_unpack - proto', () => {})
    it.skip('ne_proto2_any_unpack_bytewise_fallback - proto', () => {})
    it.skip('ne_proto3_any_unpack - proto', () => {})
    it.skip('ne_proto3_any_unpack_bytewise_fallback - proto', () => {})
  })

  describe('lt_literal', () => {
    it('lt_int', () => assertCel('-1 < 0', true))
    it('not_lt_int', () => assertCel('0 < 0', false))
    it('lt_uint', () => assertCel('0u < 1u', true))
    it('not_lt_uint', () => assertCel('2u < 2u', false))
    it('lt_double', () => assertCel('1.0 < 1.0000001', true))
    it('not_lt_double', () => assertCel('-0.0 < 0.0', false))
    it('lt_string', () => assertCel("'a' < 'b'", true))
    it('lt_string_empty_to_nonempty', () => assertCel("'' < 'a'", true))
    it('lt_string_case', () => assertCel("'Abc' < 'aBC'", true))
    it('lt_string_length', () => assertCel("'abc' < 'abcd'", true))
    it('lt_string_diacritical_mark_sensitive', () => assertCel("'a' < '\\u00E1'", true))
    it('not_lt_string_empty', () => assertCel("'' < ''", false))
    it('not_lt_string_same', () => assertCel("'abc' < 'abc'", false))
    it('not_lt_string_case_length', () => assertCel("'a' < 'AB'", false))
    it('unicode_order_lexical', () => assertCel("'f' < '\\u1EBF'", true))
    it.skip('lt_bytes - bytes comparison not supported', () => assertCel("b'a' < b'b'", true))
    it.skip('not_lt_bytes_same - bytes comparison not supported', () => assertCel("b'abc' < b'abc'", false))
    it.skip('not_lt_bytes_width', () => assertCel("b'\u00e1' < b'b'", false))
    it('lt_bool_false_first', () => assertCel('false < true', true))
    it('not_lt_bool_same', () => assertCel('true < true', false))
    it('not_lt_bool_true_first', () => assertCel('true < false', false))
    it.skip('lt_list_unsupported', () => assertCelError('[0] < [1]'))
    it.skip('lt_map_unsupported', () => assertCelError("{0:'a'} < {1:'b'}"))
    it.skip('lt_null_unsupported', () => assertCelError('null < null'))
    it.skip('lt_mixed_types_error', () => assertCelError("'foo' < 1024"))
    it('lt_dyn_int_uint', () => assertCel('dyn(1) < 2u', true))
    it('lt_dyn_int_double', () => assertCel('dyn(1) < 2.0', true))
    it('lt_dyn_uint_int', () => assertCel('dyn(1u) < 2', true))
    it('lt_dyn_uint_double', () => assertCel('dyn(1u) < 2.0', true))
    it('lt_dyn_double_int', () => assertCel('dyn(1.0) < 2', true))
    it('lt_dyn_double_uint', () => assertCel('dyn(1.0) < 2u', true))
    it('not_lt_dyn_int_uint', () => assertCel('dyn(1) < 1u', false))
    it('not_lt_dyn_int_double', () => assertCel('dyn(1) < 1.0', false))
    it('not_lt_dyn_uint_int', () => assertCel('dyn(1u) < 1', false))
    it('not_lt_dyn_uint_double', () => assertCel('dyn(1u) < 1.0', false))
    it('not_lt_dyn_double_int', () => assertCel('dyn(1.0) < 1', false))
    it('not_lt_dyn_double_uint', () => assertCel('dyn(1.0) < 1u', false))
    it('lt_dyn_int_big_uint', () => assertCel('dyn(1) < 9223372036854775808u', true))
    it('lt_dyn_small_int_uint', () => assertCel('dyn(-1) < 0u', true))
    it('not_lt_dyn_int_big_lossy_double', () => assertCel('dyn(9223372036854775807) < 9223372036854775808.0', false))
    it('lt_dyn_int_big_lossy_double', () => assertCel('dyn(9223372036854775807) < 9223372036854777857.0', true))
    it('not_lt_dyn_int_small_double', () => assertCel('dyn(9223372036854775807) < -9223372036854777857.0', false))
    it('not_lt_dyn_int_small_lossy_double', () => assertCel('dyn(-9223372036854775808) < -9223372036854775809.0', false))
    it('not_lt_dyn_uint_small_int', () => assertCel('dyn(1u) < -9223372036854775808', false))
    it('not_lt_dyn_big_uint_int', () => assertCel('dyn(9223372036854775808u) < 1', false))
    it('not_lt_dyn_uint_small_double', () => assertCel('dyn(18446744073709551615u) < -1.0', false))
    it('lt_dyn_uint_big_double', () => assertCel('dyn(18446744073709551615u) < 18446744073709590000.0', true))
    it('not_lt_dyn_big_double_uint', () => assertCel('dyn(18446744073709553665.0) < 18446744073709551615u', false))
    it('not_lt_dyn_big_double_int', () => assertCel('dyn(9223372036854775808.0) < 9223372036854775807', false))
    it('not_lt_dyn_small_double_int', () => assertCel('dyn(-9223372036854775809.0) < -9223372036854775808', false))
  })

  describe('gt_literal', () => {
    it('gt_int', () => assertCel('42 > -42', true))
    it('not_gt_int', () => assertCel('0 > 0', false))
    it('gt_uint', () => assertCel('48u > 46u', true))
    it('not_gt_uint', () => assertCel('0u > 999u', false))
    it('gt_double', () => assertCel('1e+1 > 1e+0', true))
    it('not_gt_double', () => assertCel('.99 > 9.9e-1', false))
    it('gt_string_case', () => assertCel("'abc' > 'aBc'", true))
    it('gt_string_to_empty', () => assertCel("'A' > ''", true))
    it('not_gt_string_empty_to_empty', () => assertCel("'' > ''", false))
    it('gt_string_unicode', () => assertCel("'\u03b1' > 'omega'", true))
    it.skip('gt_bytes_one', () => assertCel("b'\\x01' > b'\\x00'", true))
    it.skip('gt_bytes_one_to_empty', () => assertCel("b'\\x00' > b''", true))
    it.skip('not_gt_bytes_sorting', () => assertCel("b'\\x00\\x01' > b'\\x01'", false))
    it('gt_bool_true_false', () => assertCel('true > false', true))
    it('not_gt_bool_false_true', () => assertCel('false > true', false))
    it('not_gt_bool_same', () => assertCel('true > true', false))
    it.skip('gt_null_unsupported', () => assertCelError('null > null'))
    it.skip('gt_list_unsupported', () => assertCelError('[1] > [0]'))
    it.skip('gt_map_unsupported', () => assertCelError("{1:'b'} > {0:'a'}"))
    it.skip('gt_mixed_types_error', () => assertCelError("'foo' > 1024"))
    it('gt_dyn_int_uint', () => assertCel('dyn(2) > 1u', true))
    it('gt_dyn_int_double', () => assertCel('dyn(2) > 1.0', true))
    it('gt_dyn_uint_int', () => assertCel('dyn(2u) > 1', true))
    it('gt_dyn_uint_double', () => assertCel('dyn(2u) > 1.0', true))
    it('gt_dyn_double_int', () => assertCel('dyn(2.0) > 1', true))
    it('gt_dyn_double_uint', () => assertCel('dyn(2.0) > 1u', true))
    it('not_gt_dyn_int_uint', () => assertCel('dyn(1) > 1u', false))
    it('not_gt_dyn_int_double', () => assertCel('dyn(1) > 1.0', false))
    it('not_gt_dyn_uint_int', () => assertCel('dyn(1u) > 1', false))
    it('not_gt_dyn_uint_double', () => assertCel('dyn(1u) > 1.0', false))
    it('not_gt_dyn_double_int', () => assertCel('dyn(1.0) > 1', false))
    it('not_gt_dyn_double_uint', () => assertCel('dyn(1.0) > 1u', false))
    it('not_gt_dyn_int_big_uint', () => assertCel('dyn(1) > 9223372036854775808u', false))
    it('not_gt_dyn_small_int_uint', () => assertCel('dyn(-1) > 0u', false))
    it('not_gt_dyn_int_big_double', () => assertCel('dyn(9223372036854775807) > 9223372036854775808.0', false))
    it('not_gt_dyn_int_small_lossy_double', () => assertCel('dyn(-9223372036854775808) > -9223372036854775809.0', false))
    it('gt_dyn_int_small_lossy_double_greater', () => assertCel('dyn(-9223372036854775808) > -9223372036854777857.0', true))
    it('gt_dyn_uint_small_int', () => assertCel('dyn(1u) > -1', true))
    it('gt_dyn_big_uint_int', () => assertCel('dyn(9223372036854775808u) > 1', true))
    it('gt_dyn_uint_small_double', () => assertCel('dyn(9223372036854775807u) > -1.0', true))
    it('not_gt_dyn_uint_big_double', () => assertCel('dyn(18446744073709551615u) > 18446744073709590000.0', false))
    it('gt_dyn_big_double_uint', () => assertCel('dyn(18446744073709553665.0) > 18446744073709551615u', true))
    it('not_gt_dyn_big_double_int', () => assertCel('dyn(9223372036854775808.0) > 9223372036854775807', false))
    it('not_gt_dyn_small_double_int', () => assertCel('dyn(-9223372036854775809.0) > -9223372036854775808', false))
  })

  describe('lte_literal', () => {
    it('lte_int_lt', () => assertCel('0 <= 1', true))
    it('lte_int_eq', () => assertCel('1 <= 1', true))
    it('not_lte_int_gt', () => assertCel('1 <= -1', false))
    it('lte_uint_lt', () => assertCel('0u <= 1u', true))
    it('lte_uint_eq', () => assertCel('1u <= 1u', true))
    it('not_lte_uint_gt', () => assertCel('1u <= 0u', false))
    it('lte_double_lt', () => assertCel('0.0 <= 0.1e-31', true))
    it('lte_double_eq', () => assertCel('0.0 <= 0e-1', true))
    it('not_lte_double_gt', () => assertCel('1.0 <= 0.99', false))
    it('lte_string_empty', () => assertCel("'' <= ''", true))
    it('lte_string_from_empty', () => assertCel("'' <= 'a'", true))
    it('not_lte_string_to_empty', () => assertCel("'a' <= ''", false))
    it('lte_string_lexicographical', () => assertCel("'aBc' <= 'abc'", true))
    it('lte_string_unicode_eq', () => assertCel("'\u03b1' <= '\u03b1'", true))
    it('lte_string_unicode_lt', () => assertCel("'a' <= '\u03b1'", true))
    it('not_lte_string_unicode', () => assertCel("'\u03b1' <= 'a'", false))
    it.skip('lte_bytes_empty', () => assertCel("b'' <= b'\\x00'", true))
    it.skip('not_lte_bytes_length', () => assertCel("b'\\x01\\x00' <= b'\\x01'", false))
    it('lte_bool_false_true', () => assertCel('false <= true', true))
    it('lte_bool_false_false', () => assertCel('false <= false', true))
    it('lte_bool_true_false', () => assertCel('true <= false', false))
    it.skip('lte_null_unsupported', () => assertCelError('null <= null'))
    it.skip('lte_list_unsupported', () => assertCelError('[0] <= [0]'))
    it.skip('lte_map_unsupported', () => assertCelError("{0:'a'} <= {1:'b'}"))
    it.skip('lte_mixed_types_error', () => assertCelError("'foo' <= 1024"))
    it('lte_dyn_int_uint', () => assertCel('dyn(1) <= 2u', true))
    it('lte_dyn_int_double', () => assertCel('dyn(1) <= 2.0', true))
    it('lte_dyn_uint_int', () => assertCel('dyn(1u) <= 2', true))
    it('lte_dyn_uint_double', () => assertCel('dyn(1u) <= 2.0', true))
    it('lte_dyn_double_int', () => assertCel('dyn(1.0) <= 2', true))
    it('lte_dyn_double_uint', () => assertCel('dyn(1.0) <= 2u', true))
    it('not_lte_dyn_int_uint', () => assertCel('dyn(2) <= 1u', false))
    it('not_lte_dyn_int_double', () => assertCel('dyn(2) <= 1.0', false))
    it('not_lte_dyn_uint_int', () => assertCel('dyn(2u) <= 1', false))
    it('not_lte_dyn_uint_double', () => assertCel('dyn(2u) <= 1.0', false))
    it('not_lte_dyn_double_int', () => assertCel('dyn(2.0) <= 1', false))
    it('not_lte_dyn_double_uint', () => assertCel('dyn(2.0) <= 1u', false))
    it('lte_dyn_int_big_uint', () => assertCel('dyn(1) <= 9223372036854775808u', true))
    it('lte_dyn_small_int_uint', () => assertCel('dyn(-1) <= 0u', true))
    it('lte_dyn_int_big_double', () => assertCel('dyn(9223372036854775807) <= 9223372036854775808.0', true))
    it('lte_dyn_int_small_lossy_double', () => assertCel('dyn(-9223372036854775808) <= -9223372036854775809.0', true))
    it('not_lte_dyn_int_small_lossy_double_less', () => assertCel('dyn(-9223372036854775808) <= -9223372036854777857.0', false))
    it('not_lte_dyn_uint_small_int', () => assertCel('dyn(1u) <= -9223372036854775808', false))
    it('not_lte_dyn_big_uint_int', () => assertCel('dyn(9223372036854775808u) <= 1', false))
    it('not_lte_dyn_uint_small_double', () => assertCel('dyn(18446744073709551615u) <= -1.0', false))
    it('lte_dyn_uint_big_double', () => assertCel('dyn(18446744073709551615u) <= 18446744073709590000.0', true))
    it('not_lte_dyn_big_double_uint', () => assertCel('dyn(18446744073709553665.0) <= 18446744073709551615u', false))
    it('lte_dyn_big_double_int', () => assertCel('dyn(9223372036854775808.0) <= 9223372036854775807', true))
    it('lte_dyn_small_double_int', () => assertCel('dyn(-9223372036854775809.0) <= -9223372036854775808', true))
  })

  describe('gte_literal', () => {
    it('gte_int_gt', () => assertCel('0 >= -1', true))
    it('gte_int_eq', () => assertCel('999 >= 999', true))
    it('not_gte_int_lt', () => assertCel('999 >= 1000', false))
    it('gte_uint_gt', () => assertCel('1u >= 0u', true))
    it('gte_uint_eq', () => assertCel('0u >= 0u', true))
    it('not_gte_uint_lt', () => assertCel('1u >= 10u', false))
    it('gte_double_gt', () => assertCel('1e+1 >= 1e+0', true))
    it('gte_double_eq', () => assertCel('9.80665 >= 9.80665e+0', true))
    it('not_gte_double_lt', () => assertCel('0.9999 >= 1.0', false))
    it('gte_string_empty', () => assertCel("'' >= ''", true))
    it('gte_string_to_empty', () => assertCel("'a' >= ''", true))
    it('gte_string_empty_to_nonempty', () => assertCel("'' >= 'a'", false))
    it('gte_string_length', () => assertCel("'abcd' >= 'abc'", true))
    it('not_gte_string_lexicographical', () => assertCel("'abc' >= 'abd'", false))
    it('gte_string_unicode_eq', () => assertCel("'\u03c4' >= '\u03c4'", true))
    it('gte_string_unicode_gt', () => assertCel("'\u03c4' >= 't'", true))
    it('not_get_string_unicode', () => assertCel("'t' >= '\u03c4'", false))
    it.skip('gte_bytes_to_empty', () => assertCel("b'\\x00' >= b''", true))
    it.skip('not_gte_bytes_empty_to_nonempty', () => assertCel("b'' >= b'\\x00'", false))
    it.skip('gte_bytes_samelength', () => assertCel("b'\\x00\\x01' >= b'\\x01\\x00'", false))
    it('gte_bool_gt', () => assertCel('true >= false', true))
    it('gte_bool_eq', () => assertCel('true >= true', true))
    it('not_gte_bool_lt', () => assertCel('false >= true', false))
    it.skip('gte_null_unsupported', () => assertCelError('null >= null'))
    it.skip('gte_list_unsupported', () => assertCelError("['y'] >= ['x']"))
    it.skip('gte_map_unsupported', () => assertCelError("{1:'b'} >= {0:'a'}"))
    it.skip('gte_mixed_types_error', () => assertCelError("'foo' >= 1.0"))
    it('gte_dyn_int_uint', () => assertCel('dyn(2) >= 1u', true))
    it('gte_dyn_int_double', () => assertCel('dyn(2) >= 1.0', true))
    it('gte_dyn_uint_int', () => assertCel('dyn(2u) >= 1', true))
    it('gte_dyn_uint_double', () => assertCel('dyn(2u) >= 1.0', true))
    it('gte_dyn_double_int', () => assertCel('dyn(2.0) >= 1', true))
    it('gte_dyn_double_uint', () => assertCel('dyn(2.0) >= 1u', true))
    it('not_gte_dyn_int_uint', () => assertCel('dyn(0) >= 1u', false))
    it('not_gte_dyn_int_double', () => assertCel('dyn(0) >= 1.0', false))
    it('not_gte_dyn_uint_int', () => assertCel('dyn(0u) >= 1', false))
    it('not_gte_dyn_uint_double', () => assertCel('dyn(0u) >= 1.0', false))
    it('not_gte_dyn_double_int', () => assertCel('dyn(0.0) >= 1', false))
    it('not_gte_dyn_double_uint', () => assertCel('dyn(0.0) >= 1u', false))
  })
})

// ============================================================================
// conversions.textproto
// ============================================================================
describe('conversions', () => {
  describe('bytes', () => {
    it('string_empty', () => assertCel("bytes('')", new Uint8Array([])))
    it('string', () => assertCel("bytes('abc')", new Uint8Array([97, 98, 99])))
    it.skip('string_unicode', () => assertCel("bytes('\u00ff')", new Uint8Array([0xc3, 0xbf])))
    it.skip('string_unicode_vs_literal', () => assertCel("bytes('\\377') == b'\\377'", false))
  })

  describe('double', () => {
    it('int_zero', () => assertCel('double(0)', 0.0))
    it('int_pos', () => assertCel('double(1000000000000)', 1e12))
    it('int_neg', () => assertCel('double(-1000000000000000)', -1e15))
    it('int_min_exact', () => assertCel('double(-9007199254740992)', -9.007199254740992e15))
    it('int_max_exact', () => assertCel('double(9007199254740992)', 9.007199254740992e15))
    it('int_range', () => assertCel('double(9223372036854775807)', 9.223372036854776e18))
    it('uint_zero', () => assertCel('double(0u)', 0.0))
    it('uint_pos', () => assertCel('double(123u)', 123.0))
    it('uint_max_exact', () => assertCel('double(9007199254740992u)', 9.007199254740992e15))
    it('uint_range', () => assertCel('double(18446744073709551615u)', 1.8446744073709552e19))
    it('string_zero', () => assertCel("double('0')", 0.0))
    it('string_zero_dec', () => assertCel("double('0.0')", 0.0))
    it('string_neg_zero', () => assertCel("double('-0.0')", -0.0))
    it('string_no_dec', () => assertCel("double('123')", 123.0))
    it('string_pos', () => assertCel("double('123.456')", 123.456))
    it('string_neg', () => assertCel("double('-987.654')", -987.654))
    it('string_exp_pos_pos', () => assertCel("double('6.02214e23')", 6.02214e23))
    it('string_exp_pos_neg', () => assertCel("double('1.38e-23')", 1.38e-23))
    it('string_exp_neg_pos', () => assertCel("double('-84.32e7')", -8.432e8))
    it('string_exp_neg_neg', () => assertCel("double('-5.43e-21')", -5.43e-21))
  })

  describe('dyn', () => {
    it('dyn_heterogeneous_list', () => assertCel("type(dyn([1, 'one']))", 'list'))
  })

  describe('int', () => {
    it('uint', () => assertCel('int(42u)', 42n))
    it('uint_zero', () => assertCel('int(0u)', 0n))
    it('uint_max_exact', () => assertCel('int(9223372036854775807u)', 9223372036854775807n))
    it.skip('uint_range - no range check', () => assertCelError('int(18446744073709551615u)'))
    it('double_round_neg', () => assertCel('int(-123.456)', -123n))
    it('double_truncate', () => assertCel('int(1.9)', 1n))
    it('double_truncate_neg', () => assertCel('int(-7.9)', -7n))
    it('double_half_pos', () => assertCel('int(11.5)', 11n))
    it('double_half_neg', () => assertCel('int(-3.5)', -3n))
    it.skip('double_big_exact', () => assertCel('int(double(36028797018963968))', 36028797018963968n))
    it.skip('double_big_precision', () => assertCel('int(double(36028797018963969))', 36028797018963968n))
    it.skip('double_int_max_range - no range check', () => assertCelError('int(9223372036854775807.0)'))
    it.skip('double_int_min_range - no range check', () => assertCelError('int(-9223372036854775808.0)'))
    it.skip('double_range - no range check', () => assertCelError('int(1e99)'))
    it('string', () => assertCel("int('987')", 987n))
    it('timestamp', () => assertCel("int(timestamp('2004-09-16T23:59:59Z'))", 1095379199n))
  })

  describe('string_conversion', () => {
    it('int', () => assertCel('string(123)', '123'))
    it('int_neg', () => assertCel('string(-456)', '-456'))
    it('uint', () => assertCel('string(9876u)', '9876'))
    it('double', () => assertCel('string(123.456)', '123.456'))
    it('double_hard', () => assertCel('string(-4.5e-3)', '-0.0045'))
    it('bytes', () => assertCel("string(b'abc')", 'abc'))
    it('bytes_unicode', () => assertCel("string(b'\\303\\277')", '\u00ff'))
    it.skip('bytes_invalid', () => assertCelError("string(b'\\000\\xff')"))
  })

  describe('type', () => {
    it.skip('bool', () => assertCel('type(true)', 'bool'))
    it.skip('bool_denotation', () => assertCel('bool', 'bool'))
    it.skip('int', () => assertCel('type(0)', 'int'))
    it.skip('int_denotation', () => assertCel('int', 'int'))
    it.skip('eq_same', () => assertCel('type(true) == type(false)', true))
    it.skip('uint', () => assertCel('type(64u)', 'uint'))
    it.skip('uint_denotation', () => assertCel('uint', 'uint'))
    it.skip('double', () => assertCel('type(3.14)', 'double'))
    it.skip('double_denotation', () => assertCel('double', 'double'))
    it.skip('null_type', () => assertCel('type(null)', 'null_type'))
    it.skip('null_type_denotation', () => assertCel('null_type', 'null_type'))
    it.skip('string', () => assertCel("type('foo')", 'string'))
    it.skip('string_denotation', () => assertCel('string', 'string'))
    it.skip('bytes', () => assertCel("type(b'\\xff')", 'bytes'))
    it.skip('bytes_denotation', () => assertCel('bytes', 'bytes'))
    it.skip('list', () => assertCel('type([1, 2, 3])', 'list'))
    it.skip('list_denotation', () => assertCel('list', 'list'))
    it.skip('lists_monomorphic', () => assertCel("type([1, 2, 3]) == type(['one', 'two', 'three'])", true))
    it.skip('map', () => assertCel('type({4: 16})', 'map'))
    it.skip('map_denotation', () => assertCel('map', 'map'))
    it.skip('map_monomorphic', () => assertCel("type({'one': 1}) == type({1: 'one'})", true))
    it.skip('eq_diff', () => assertCel('type(7) == type(7u)', false))
    it.skip('neq_same', () => assertCel('type(0.0) != type(-0.0)', false))
    it.skip('neq_diff', () => assertCel('type(0.0) != type(0)', true))
    it.skip('meta', () => assertCel('type(type(7)) == type(type(7u))', true))
    it.skip('type', () => assertCel('type(int)', 'type'))
    it.skip('type_denotation', () => assertCel('type', 'type'))
    it.skip('type_type', () => assertCel('type(type)', 'type'))
  })

  describe('uint', () => {
    it('int', () => assertCel('uint(1729)', 1729n))
    it('int_max', () => assertCel('uint(9223372036854775807)', 9223372036854775807n))
    it('int_neg', () => assertCelError('uint(-1)'))
    it('double', () => assertCel('uint(3.14159265)', 3n))
    it('double_truncate', () => assertCel('uint(1.9)', 1n))
    it('double_half', () => assertCel('uint(25.5)', 25n))
    it.skip('double_big_exact', () => assertCel('uint(double(36028797018963968u))', 36028797018963968n))
    it.skip('double_big_precision', () => assertCel('uint(double(36028797018963969u))', 36028797018963968n))
    it.skip('double_uint_max_range - no range check', () => assertCelError('int(18446744073709551615.0)'))
    it.skip('double_range_beyond_uint - no range check', () => assertCelError('uint(6.022e23)'))
    it('string', () => assertCel("uint('300')", 300n))
  })

  describe('bool', () => {
    it.skip('string_1', () => assertCel("bool('1')", true))
    it.skip('string_t', () => assertCel("bool('t')", true))
    it('string_true_lowercase', () => assertCel("bool('true')", true))
    it.skip('string_true_uppercase', () => assertCel("bool('TRUE')", true))
    it.skip('string_true_pascalcase', () => assertCel("bool('True')", true))
    it.skip('string_0', () => assertCel("bool('0')", false))
    it.skip('string_f', () => assertCel("bool('f')", false))
    it('string_false_lowercase', () => assertCel("bool('false')", false))
    it.skip('string_false_uppercase', () => assertCel("bool('FALSE')", false))
    it.skip('string_false_pascalcase', () => assertCel("bool('False')", false))
    it.skip('string_true_badcase', () => assertCelError("bool('TrUe')"))
    it.skip('string_false_badcase', () => assertCelError("bool('FaLsE')"))
  })

  describe('identity', () => {
    it('bool', () => assertCel('bool(true)', true))
    it('int', () => assertCel('int(1)', 1n))
    it('uint', () => assertCel('uint(1u)', 1n))
    it('double', () => assertCel('double(5.5)', 5.5))
    it('string', () => assertCel("string('hello')", 'hello'))
    it.skip('bytes', () => assertCel("bytes(b'abc')", new Uint8Array([97, 98, 99])))
    it.skip('duration', () => assertCel("duration(duration('100s')) == duration('100s')", true))
    it.skip('timestamp', () => assertCel('timestamp(timestamp(1000000000)) == timestamp(1000000000)', true))
  })
})

// ============================================================================
// fp_math.textproto
// ============================================================================
describe('fp_math', () => {
  describe('fp_math', () => {
    it('add_positive_positive', () => assertCel('4.25 + 15.25', 19.5))
    it('add_positive_negative', () => assertCel('17.75 + (-7.75)', 10.0))
    it('add_negative_negative', () => assertCel('-4.125 + (-2.125)', -6.25))
    it('sub_positive_positive', () => assertCel('42.0 - 12.0', 30.0))
    it('sub_positive_negative', () => assertCel('42.875 - (-22.0)', 64.875))
    it('sub_negative_negative', () => assertCel('-4.875 - (-0.125)', -4.75))
    it('multiply_positive_positive', () => assertCel('42.5 * 0.2', 8.5))
    it('multiply_positive_negative', () => assertCel('40.75 * (-2.25)', -91.6875))
    it('multiply_negative_negative', () => assertCel('-3.0 * (-2.5)', 7.5))
    it('divide_positive_positive', () => assertCel('0.0625 / 0.002', 31.25))
    it('divide_positive_negative', () => assertCel('-2.0 / 2.0', -1.0))
    it('divide_negative_negative', () => assertCel('-8.875 / (-0.0625)', 142.0))
    it('mod_not_support', () => assertCelError('47.5 % 5.5'))
    it('negative', () => assertCel('-(4.5)', -4.5))
    it('double_negative', () => assertCel('-(-1.25)', 1.25))
    it('negative_zero', () => assertCel('-(0.0)', -0.0))
    it('divide_zero', () => assertCel('15.75 / 0.0', Infinity))
    it('multiply_zero', () => assertCel('15.36 * 0.0', 0.0))
    it('add_left_identity', () => assertCel('0.0 + 1.75', 1.75))
    it('add_right_identity', () => assertCel('2.5 + 0.0', 2.5))
    it('add_commutative', () => assertCel('7.5 + 1.5 == 1.5 + 7.5', true))
    it('add_associative', () => assertCel('5.625 + (15.75 + 2.0) == (5.625 + 15.75) + 2.0', true))
    it('mul_left_identity', () => assertCel('1.0 * 45.25', 45.25))
    it('mul_right_identity', () => assertCel('-25.25 * 1.0', -25.25))
    it('mul_commutative', () => assertCel('1.5 * 25.875 == 25.875 * 1.5', true))
    it('mul_associative', () => assertCel('1.5 * (23.625 * 0.75) == (1.5 * 23.625) * 0.75', true))
    it('add_mul_distribute', () => assertCel('5.75 * (1.5 + 2.5) == 5.75 * 1.5 + 5.75 * 2.5', true))
    it('fp_overflow_positive', () => assertCel('2.0 * 8.988466e+307', Infinity))
    it('fp_overflow_negative', () => assertCel('2.0 * -8.988466e+307', -Infinity))
    it('fp_underflow', () => assertCel('1e-324 / 2.0', 0.0))
  })
})

// ============================================================================
// integer_math.textproto
// ============================================================================
describe('integer_math', () => {
  describe('int64_math', () => {
    it('add_positive_positive', () => assertCel('40 + 2', 42n))
    it('add_positive_negative', () => assertCel('42 + (-7)', 35n))
    it('add_negative_negative', () => assertCel('-4 + (-2)', -6n))
    it('sub_positive_positive', () => assertCel('42 - 12', 30n))
    it('sub_positive_negative', () => assertCel('42 - (-22)', 64n))
    it('sub_negative_negative', () => assertCel('-42 - (-12)', -30n))
    it('multiply_positive_positive', () => assertCel('42 * 2', 84n))
    it('multiply_positive_negative', () => assertCel('40 * (-2)', -80n))
    it('multiply_negative_negative', () => assertCel('-30 * (-2)', 60n))
    it('divide_positive_positive', () => assertCel('42 / 2', 21n))
    it('divide_positive_negative', () => assertCel('-20 / 2', -10n))
    it('divide_negative_negative', () => assertCel('-80 / (-2)', 40n))
    it('mod_positive_positive', () => assertCel('47 % 5', 2n))
    it('mod_positive_negative', () => assertCel('43 % (-5)', 3n))
    it('mod_negative_negative', () => assertCel('-42 % (-5)', -2n))
    it('mod_negative_positive', () => assertCel('-3 % 5', -3n))
    it('unary_minus_pos', () => assertCel('-(42)', -42n))
    it('unary_minus_neg', () => assertCel('-(-42)', 42n))
    it.skip('unary_minus_no_overload - no overload check for uint negation', () => assertCelError('-(42u)'))
    it.skip('unary_minus_not_bool', () => assertCelError('-false'))
    it('mod_zero', () => assertCelError('34 % 0'))
    it('negative_zero', () => assertCel('-(0)', 0n))
    it('double_negative', () => assertCel('-(-42)', 42n))
    it('divide_zero', () => assertCelError('15 / 0'))
    it('multiply_zero', () => assertCel('15 * 0', 0n))
    it('add_left_identity', () => assertCel('0 + 17', 17n))
    it('add_right_identity', () => assertCel('29 + 0', 29n))
    it('add_commutative', () => assertCel('75 + 15 == 15 + 75', true))
    it('add_associative', () => assertCel('5 + (15 + 20) == (5 + 15) + 20', true))
    it('mul_left_identity', () => assertCel('1 * 45', 45n))
    it('mul_right_identity', () => assertCel('-25 * 1', -25n))
    it('mul_commutative', () => assertCel('15 * 25 == 25 * 15', true))
    it('mul_associative', () => assertCel('15 * (23 * 88) == (15 * 23) * 88', true))
    it('add_mul_distribute', () => assertCel('5 * (15 + 25) == 5 * 15 + 5 * 25', true))
    it('int64_overflow_positive', () => assertCelError('9223372036854775807 + 1'))
    it('int64_overflow_negative', () => assertCelError('-9223372036854775808 - 1'))
    it('int64_overflow_add_negative', () => assertCelError('-9223372036854775808 + (-1)'))
    it('int64_overflow_sub_positive', () => assertCelError('1 - (-9223372036854775807)'))
    it.skip('int64_min_negate - no overflow check on negate', () => assertCelError('-(-9223372036854775808)'))
    it('int64_min_negate_mul', () => assertCelError('(-9223372036854775808) * -1'))
    it('int64_min_negate_div', () => assertCelError('(-9223372036854775808)/-1'))
    it('int64_overflow_mul_positive', () => assertCelError('5000000000 * 5000000000'))
    it('int64_overflow_mul_negative', () => assertCelError('(-5000000000) * 5000000000'))
    it('uint64_overflow_positive', () => assertCelError('18446744073709551615u + 1u'))
    it.skip('uint64_overflow_negative - no uint underflow check', () => assertCelError('0u - 1u'))
    it('uint64_overflow_mul_positive', () => assertCelError('5000000000u * 5000000000u'))
  })

  describe('uint64_math', () => {
    it('add', () => assertCel('42u + 2u', 44n))
    it('sub', () => assertCel('42u - 12u', 30n))
    it('multiply', () => assertCel('40u * 2u', 80n))
    it('divide', () => assertCel('60u / 2u', 30n))
    it('mod', () => assertCel('42u % 5u', 2n))
    it.skip('negative_no_overload - no overload check for uint negation', () => assertCelError('-(5u)'))
    it('mod_zero', () => assertCelError('34u % 0u'))
    it('divide_zero', () => assertCelError('15u / 0u'))
    it('multiply_zero', () => assertCel('15u * 0u', 0n))
    it('add_left_identity', () => assertCel('0u + 17u', 17n))
    it('add_right_identity', () => assertCel('29u + 0u', 29n))
    it('add_commutative', () => assertCel('75u + 15u == 15u + 75u', true))
    it('add_associative', () => assertCel('5u + (15u + 20u) == (5u + 15u) + 20u', true))
    it('mul_left_identity', () => assertCel('1u * 45u', 45n))
    it('mul_right_identity', () => assertCel('25u * 1u', 25n))
    it('mul_commutative', () => assertCel('15u * 25u == 25u * 15u', true))
    it('mul_associative', () => assertCel('15u * (23u * 88u) == (15u * 23u) * 88u', true))
    it('add_mul_distribute', () => assertCel('5u * (15u + 25u) == 5u * 15u + 5u * 25u', true))
  })
})

// ============================================================================
// lists.textproto
// ============================================================================
describe('lists', () => {
  describe('concatenation', () => {
    it('list_append', () => assertCel('[0, 1, 2] + [3, 4, 5] == [0, 1, 2, 3, 4, 5]', true))
    it('list_not_commutative', () => assertCel('[0, 1, 2] + [3, 4, 5] == [3, 4, 5, 0, 1, 2]', false))
    it('list_repeat', () => assertCel('[2] + [2]', [2n, 2n]))
    it('empty_empty', () => assertCel('[] + []', []))
    it('left_unit', () => assertCel('[] + [3, 4]', [3n, 4n]))
    it('right_unit', () => assertCel('[1, 2] + []', [1n, 2n]))
  })

  describe('index', () => {
    it('zero_based', () => assertCel('[7, 8, 9][0]', 7n))
    it('zero_based_double', () => assertCel('[7, 8, 9][dyn(0.0)]', 7n))
    it('zero_based_double_error', () => assertCelError('[7, 8, 9][dyn(0.1)]'))
    it('zero_based_uint', () => assertCel('[7, 8, 9][dyn(0u)]', 7n))
    it('singleton', () => assertCel("['foo'][0]", 'foo'))
    it('middle', () => assertCel('[0, 1, 1, 2, 3, 5, 8, 13][4]', 3n))
    it('last', () => assertCel("['George', 'John', 'Paul', 'Ringo'][3]", 'Ringo'))
    it('index_out_of_bounds', () => assertCelError('[1, 2, 3][3]'))
    it('index_out_of_bounds_or_false', () => assertCelError('dyn([1, 2, 3][3]) || false'))
    it('index_out_of_bounds_or_true', () => assertCel('dyn([1, 2, 3][3]) || true', true))
    it('index_out_of_bounds_and_false', () => assertCel('dyn([1, 2, 3][3]) && false', false))
    it('index_out_of_bounds_and_true', () => assertCelError('dyn([1, 2, 3][3]) && true'))
    it('bad_index_type', () => assertCelError("[1, 2, 3][dyn('')]"))
    it('bad_index_type_or_false', () => assertCelError("dyn([1, 2, 3][dyn('')]) || false"))
    it('bad_index_type_or_true', () => assertCel("dyn([1, 2, 3][dyn('')]) || true", true))
    it('bad_index_type_and_false', () => assertCel("dyn([1, 2, 3][dyn('')]) && false", false))
    it('bad_index_type_and_true', () => assertCelError("dyn([1, 2, 3][dyn('')]) && true"))
  })

  describe('in', () => {
    it('empty', () => assertCel('7 in []', false))
    it('singleton', () => assertCel('4u in [4u]', true))
    it('first', () => assertCel("'alpha' in ['alpha', 'beta', 'gamma']", true))
    it('middle', () => assertCel('3 in [5, 4, 3, 2, 1]', true))
    it('last', () => assertCel('20u in [4u, 6u, 8u, 12u, 20u]', true))
    it('double_in_ints', () => assertCel('dyn(3.0) in [5, 4, 3, 2, 1]', true))
    it('uint_in_ints', () => assertCel('dyn(3u) in [5, 4, 3, 2, 1]', true))
    it('int_in_doubles', () => assertCel('dyn(3) in [5.0, 4.0, 3.0, 2.0, 1.0]', true))
    it('uint_in_doubles', () => assertCel('dyn(3u) in [5.0, 4.0, 3.0, 2.0, 1.0]', true))
    it('int_in_uints', () => assertCel('dyn(3) in [5u, 4u, 3u, 2u, 1u]', true))
    it('double_in_uints', () => assertCel('dyn(3.0) in [5u, 4u, 3u, 2u, 1u]', true))
    it('missing', () => assertCel("'hawaiian' in ['meat', 'veggie', 'margarita', 'cheese']", false))
  })

  describe('size', () => {
    it('list_empty', () => assertCel('size([])', 0n))
    it('list', () => assertCel('size([1, 2, 3])', 3n))
    it('map_empty', () => assertCel('size({})', 0n))
    it('map', () => assertCel("size({1: 'one', 2: 'two', 3: 'three'})", 3n))
  })
})

// ============================================================================
// logic.textproto
// ============================================================================
describe('logic', () => {
  describe('conditional', () => {
    it('true_case', () => assertCel('true ? 1 : 2', 1n))
    it('false_case', () => assertCel("false ? 'foo' : 'bar'", 'bar'))
    it.skip('error_case - div/0 in condition not detected', () => assertCelError("2 / 0 > 4 ? 'baz' : 'quux'"))
    it.skip('mixed_type', () => assertCel("true ? 'cows' : 17", 'cows'))
    it.skip('bad_type', () => assertCelError("'cows' ? false : 17"))
  })

  describe('AND', () => {
    it('all_true', () => assertCel('true && true', true))
    it('all_false', () => assertCel('false && false', false))
    it('false_left', () => assertCel('false && true', false))
    it('false_right', () => assertCel('true && false', false))
    it('short_circuit_type_left', () => assertCel('false && 32', false))
    it('short_circuit_type_right', () => assertCel("'horses' && false", false))
    it('short_circuit_error_left', () => assertCel('false && (2 / 0 > 3 ? false : true)', false))
    it('short_circuit_error_right', () => assertCel('(2 / 0 > 3 ? false : true) && false', false))
    it.skip('error_right - div/0 error not propagated through &&', () => assertCelError('true && 1/0 != 0'))
    it.skip('error_left - div/0 error not propagated through &&', () => assertCelError('1/0 != 0 && true'))
    it.skip('no_overload', () => assertCelError("'less filling' && 'tastes great'"))
  })

  describe('OR', () => {
    it('all_true', () => assertCel('true || true', true))
    it('all_false', () => assertCel('false || false', false))
    it('false_left', () => assertCel('false || true', true))
    it('false_right', () => assertCel('true || false', true))
    it('short_circuit_type_left', () => assertCel('true || 32', true))
    it('short_circuit_type_right', () => assertCel("'horses' || true", true))
    it('short_circuit_error_left', () => assertCel('true || (2 / 0 > 3 ? false : true)', true))
    it('short_circuit_error_right', () => assertCel('(2 / 0 > 3 ? false : true) || true', true))
    it.skip('error_right - div/0 error not propagated through ||', () => assertCelError('false || 1/0 != 0'))
    it.skip('error_left - div/0 error not propagated through ||', () => assertCelError('1/0 != 0 || false'))
    it.skip('no_overload', () => assertCelError("'less filling' || 'tastes great'"))
  })

  describe('NOT', () => {
    it('not_true', () => assertCel('!true', false))
    it('not_false', () => assertCel('!false', true))
    it('no_overload', () => assertCelError('!0'))
  })
})

// ============================================================================
// macros.textproto
// ============================================================================
describe('macros', () => {
  describe('exists', () => {
    it('list_elem_all_true', () => assertCel('[1, 2, 3].exists(e, e > 0)', true))
    it('list_elem_some_true', () => assertCel('[1, 2, 3].exists(e, e == 2)', true))
    it('list_elem_none_true', () => assertCel('[1, 2, 3].exists(e, e > 3)', false))
    it.skip('list_elem_type_shortcircuit', () => assertCel("[1, 'foo', 3].exists(e, e != '1')", true))
    it.skip('list_elem_type_exhaustive', () => assertCel("[1, 'foo', 3].exists(e, e == '10')", false))
    it('list_elem_exists_error', () => assertCelError('[1, 2, 3].exists(e, e / 0 == 17)'))
    it('list_empty', () => assertCel('[].exists(e, e == 2)', false))
    it('map_key', () => assertCel("{'key1':1, 'key2':2}.exists(k, k == 'key2')", true))
    it('not_map_key', () => assertCel("!{'key1':1, 'key2':2}.exists(k, k == 'key3')", true))
    it.skip('map_key_type_shortcircuit', () => assertCel("{'key':1, 1:21}.exists(k, k != 2)", true))
    it.skip('map_key_type_exhaustive', () => assertCel("!{'key':1, 1:42}.exists(k, k == 2)", true))
  })

  describe('all', () => {
    it('list_elem_all_true', () => assertCel('[1, 2, 3].all(e, e > 0)', true))
    it('list_elem_some_true', () => assertCel('[1, 2, 3].all(e, e == 2)', false))
    it('list_elem_none_true', () => assertCel('[1, 2, 3].all(e, e == 17)', false))
    it.skip('list_elem_type_shortcircuit', () => assertCel("[1, 'foo', 3].all(e, e == 1)", false))
    it.skip('list_elem_type_exhaustive', () => assertCelError("[1, 'foo', 3].all(e, e % 2 == 1)"))
    it.skip('list_elem_error_shortcircuit', () => assertCel('[1, 2, 3].all(e, 6 / (2 - e) == 6)', false))
    it.skip('list_elem_error_exhaustive - div/0 not propagated in all()', () => assertCelError('[1, 2, 3].all(e, e / 0 != 17)'))
    it('list_empty', () => assertCel('[].all(e, e > 0)', true))
    it('map_key', () => assertCel("{'key1':1, 'key2':2}.all(k, k == 'key2')", false))
  })

  describe('exists_one', () => {
    it('list_empty', () => assertCel('[].exists_one(a, a == 7)', false))
    it('list_one_true', () => assertCel('[7].exists_one(a, a == 7)', true))
    it('list_one_false', () => assertCel('[8].exists_one(a, a == 7)', false))
    it('list_none', () => assertCel('[1, 2, 3].exists_one(x, x > 20)', false))
    it('list_one', () => assertCel('[6, 7, 8].exists_one(foo, foo % 5 == 2)', true))
    it('list_many', () => assertCel('[0, 1, 2, 3, 4].exists_one(n, n % 2 == 1)', false))
    it('list_all', () => assertCel("['foal', 'foo', 'four'].exists_one(n, n.startsWith('fo'))", false))
    it.skip('list_no_shortcircuit - div/0 not propagated in exists_one()', () => assertCelError('[3, 2, 1, 0].exists_one(n, 12 / n > 1)'))
    it.skip('map_one', () => assertCel("{6: 'six', 7: 'seven', 8: 'eight'}.exists_one(foo, foo % 5 == 2)", true))
  })

  describe('map', () => {
    it('list_empty', () => assertCel('[].map(n, n / 2)', []))
    it('list_one', () => assertCel('[3].map(n, n * n)', [9n]))
    it('list_many', () => assertCel('[2, 4, 6].map(n, n / 2)', [1n, 2n, 3n]))
    it.skip('list_error - div/0 not propagated in map()', () => assertCelError('[2, 1, 0].map(n, 4 / n)'))
    it('map_extract_keys', () => assertCel("{'John': 'smart'}.map(key, key) == ['John']", true))
  })

  describe('filter', () => {
    it('list_empty', () => assertCel('[].filter(n, n % 2 == 0)', []))
    it('list_one_true', () => assertCel('[2].filter(n, n == 2)', [2n]))
    it('list_one_false', () => assertCel('[1].filter(n, n > 3)', []))
    it('list_none', () => assertCel('[1, 2, 3].filter(e, e > 3)', []))
    it('list_some', () => assertCel('[0, 1, 2, 3, 4].filter(x, x % 2 == 1)', [1n, 3n]))
    it('list_all', () => assertCel('[1, 2, 3].filter(n, n > 0)', [1n, 2n, 3n]))
    it.skip('list_no_shortcircuit - div/0 not propagated in filter()', () => assertCelError('[3, 2, 1, 0].filter(n, 12 / n > 4)'))
    it.skip('map_filter_keys', () => assertCel("{'John': 'smart', 'Paul': 'cute', 'George': 'quiet', 'Ringo': 'funny'}.filter(key, key == 'Ringo') == ['Ringo']", true))
  })

  describe('nested', () => {
    it.skip('filter_all - nested macro compilation error', () => assertCel("['signer'].filter(signer, ['artifact'].all(artifact, true))", ['signer']))
    it('all_all', () => assertCel("['signer'].all(signer, ['artifact'].all(artifact, true))", true))
  })
})

// ============================================================================
// string.textproto
// ============================================================================
describe('string', () => {
  describe('size', () => {
    it('empty', () => assertCel("size('')", 0n))
    it('one_ascii', () => assertCel("size('A')", 1n))
    it('one_unicode', () => assertCel("size('\u00ff')", 1n))
    it('ascii', () => assertCel("size('four')", 4n))
    it('unicode', () => assertCel("size('\u03c0\u03ad\u03bd\u03c4\u03b5')", 5n))
    it('bytes_empty', () => assertCel("size(b'')", 0n))
    it('bytes', () => assertCel("size(b'abc')", 3n))
  })

  describe('starts_with', () => {
    it('basic_true', () => assertCel("'foobar'.startsWith('foo')", true))
    it('basic_false', () => assertCel("'foobar'.startsWith('bar')", false))
    it('empty_target', () => assertCel("''.startsWith('foo')", false))
    it('empty_arg', () => assertCel("'foobar'.startsWith('')", true))
    it('empty_empty', () => assertCel("''.startsWith('')", true))
    it('unicode', () => assertCel("'\u0437\u0430\u0432\u0442\u0440\u0430'.startsWith('\u0437\u0430')", true))
    it('unicode_smp', () => assertCel("'\\U0001F431\\U0001F600\\U0001F61B'.startsWith('\\U0001F431')", true))
  })

  describe('ends_with', () => {
    it('basic_true', () => assertCel("'foobar'.endsWith('bar')", true))
    it('basic_false', () => assertCel("'foobar'.endsWith('foo')", false))
    it('empty_target', () => assertCel("''.endsWith('foo')", false))
    it('empty_arg', () => assertCel("'foobar'.endsWith('')", true))
    it('empty_empty', () => assertCel("''.endsWith('')", true))
    it('unicode', () => assertCel("'fort\u00e9'.endsWith('t\u00e9')", true))
    it('unicode_smp', () => assertCel("'\\U0001F431\\U0001F600\\U0001F61B'.endsWith('\\U0001F61B')", true))
  })

  describe('matches', () => {
    it('basic', () => assertCel("'hubba'.matches('ubb')", true))
    it('empty_target', () => assertCel("''.matches('foo|bar')", false))
    it('empty_arg', () => assertCel("'cows'.matches('')", true))
    it('empty_empty', () => assertCel("''.matches('')", true))
    it('re_concat', () => assertCel("'abcd'.matches('bc')", true))
    it('re_alt', () => assertCel("'grey'.matches('gr(a|e)y')", true))
    it('re_rep', () => assertCel("'banana'.matches('ba(na)*')", true))
    it('unicode', () => assertCel("'ma\u00f1ana'.matches('a+\u00f1+a+')", true))
    it('unicode_smp', () => assertCel("'\\U0001F431\\U0001F600\\U0001F600'.matches('(a|\\U0001F600){2}')", true))
  })

  describe('concatenation', () => {
    it('concat_true', () => assertCel("'he' + 'llo'", 'hello'))
    it('concat_with_spaces', () => assertCel("'hello' + ' ' == 'hello'", false))
    it('concat_empty_string_beginning', () => assertCel("'' + 'abc'", 'abc'))
    it('concat_empty_string_end', () => assertCel("'abc' + ''", 'abc'))
    it('concat_empty_with_empty', () => assertCel("'' + ''", ''))
    it('unicode_unicode', () => assertCel("'\u00a2' + '\u00ff' + '\u0200'", '\u00a2\u00ff\u0200'))
    it('ascii_unicode', () => assertCel("'r' + '\u00f4' + 'le'", 'r\u00f4le'))
    it('ascii_unicode_unicode_smp', () => assertCel("'a' + '\u00ff' + '\\U0001F431'", 'a\u00ff\u{1f431}'))
    it('empty_unicode', () => assertCel("'' + '\u03a9' + ''", '\u03a9'))
  })

  describe('contains', () => {
    it('contains_true', () => assertCel("'hello'.contains('he')", true))
    it('contains_empty', () => assertCel("'hello'.contains('')", true))
    it('contains_false', () => assertCel("'hello'.contains('ol')", false))
    it('contains_multiple', () => assertCel("'abababc'.contains('ababc')", true))
    it('contains_unicode', () => assertCel("'Stra\u00dfe'.contains('a\u00df')", true))
    it('contains_unicode_smp', () => assertCel("'\\U0001F431\\U0001F600\\U0001F601'.contains('\\U0001F600')", true))
    it('empty_contains', () => assertCel("''.contains('something')", false))
    it('empty_empty', () => assertCel("''.contains('')", true))
  })

  describe('bytes_concat', () => {
    it.skip('concat', () => assertCel("b'abc' + b'def'", new Uint8Array([97, 98, 99, 100, 101, 102])))
    it.skip('left_unit', () => {})
    it.skip('right_unit', () => {})
    it.skip('empty_empty', () => assertCel("b'' + b''", new Uint8Array([])))
  })
})

// ============================================================================
// timestamps.textproto
// ============================================================================
describe('timestamps', () => {
  describe('timestamp_conversions', () => {
    it('toInt_timestamp', () => assertCel("int(timestamp('2009-02-13T23:31:30Z'))", 1234567890n))
    it('toString_timestamp', () => assertCel("string(timestamp('2009-02-13T23:31:30Z'))", '2009-02-13T23:31:30Z'))
    it.skip('toString_timestamp_nanos - nanosecond precision not supported', () => assertCel("string(timestamp('9999-12-31T23:59:59.999999999Z'))", '9999-12-31T23:59:59.999999999Z'))
    it.skip('toType_timestamp - type() returns object not string', () => assertCel("type(timestamp('2009-02-13T23:31:30Z'))", 'google.protobuf.Timestamp'))
    it.skip('type_comparison - type() returns object not string', () => assertCel("google.protobuf.Timestamp == type(timestamp('2009-02-13T23:31:30Z'))", true))
  })

  describe('duration_conversions', () => {
    it('toString_duration', () => assertCel("string(duration('1000000s'))", '1000000s'))
    it.skip('toType_duration - type() returns object not string', () => assertCel("type(duration('1000000s'))", 'google.protobuf.Duration'))
    it.skip('type_comparison - type() returns object not string', () => assertCel("google.protobuf.Duration == type(duration('1000000s'))", true))
  })

  describe('timestamp_selectors', () => {
    it('getDate', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDate()", 13n))
    it('getDayOfMonth', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfMonth()", 12n))
    it('getDayOfWeek', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfWeek()", 5n))
    it('getDayOfYear', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfYear()", 43n))
    it('getFullYear', () => assertCel("timestamp('2009-02-13T23:31:30Z').getFullYear()", 2009n))
    it('getHours', () => assertCel("timestamp('2009-02-13T23:31:30Z').getHours()", 23n))
    it('getMilliseconds', () => assertCel("timestamp('2009-02-13T23:31:20.123456789Z').getMilliseconds()", 123n))
    it('getMinutes', () => assertCel("timestamp('2009-02-13T23:31:30Z').getMinutes()", 31n))
    it('getMonth', () => assertCel("timestamp('2009-02-13T23:31:30Z').getMonth()", 1n))
    it('getSeconds', () => assertCel("timestamp('2009-02-13T23:31:30Z').getSeconds()", 30n))
  })

  describe('timestamp_selectors_tz', () => {
    it('getDate', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDate('Australia/Sydney')", 14n))
    it('getDayOfMonth_name_pos', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfMonth('US/Central')", 12n))
    it('getDayOfMonth_numerical_pos', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfMonth('+11:00')", 13n))
    it('getDayOfMonth_numerical_neg', () => assertCel("timestamp('2009-02-13T02:00:00Z').getDayOfMonth('-02:30')", 11n))
    it('getDayOfMonth_name_neg', () => assertCel("timestamp('2009-02-13T02:00:00Z').getDayOfMonth('America/St_Johns')", 11n))
    it('getDayOfWeek', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfWeek('UTC')", 5n))
    it('getDayOfYear', () => assertCel("timestamp('2009-02-13T23:31:30Z').getDayOfYear('US/Central')", 43n))
    it('getFullYear', () => assertCel("timestamp('2009-02-13T23:31:30Z').getFullYear('-09:30')", 2009n))
    it('getHours', () => assertCel("timestamp('2009-02-13T23:31:30Z').getHours('02:00')", 1n))
    it('getMinutes', () => assertCel("timestamp('2009-02-13T23:31:30Z').getMinutes('Asia/Kathmandu')", 16n))
    it('getMonth', () => assertCel("timestamp('2009-02-13T23:31:30Z').getMonth('UTC')", 1n))
    it('getSeconds', () => assertCel("timestamp('2009-02-13T23:31:30Z').getSeconds('-00:00')", 30n))
  })

  describe('timestamp_equality', () => {
    it('eq_same', () => assertCel("timestamp('2009-02-13T23:31:30Z') == timestamp('2009-02-13T23:31:30Z')", true))
    it('eq_diff', () => assertCel("timestamp('2009-02-13T23:31:29Z') == timestamp('2009-02-13T23:31:30Z')", false))
    it('neq_same', () => assertCel("timestamp('1945-05-07T02:41:00Z') != timestamp('1945-05-07T02:41:00Z')", false))
    it('neq_diff', () => assertCel("timestamp('2000-01-01T00:00:00Z') != timestamp('2001-01-01T00:00:00Z')", true))
  })

  describe('duration_equality', () => {
    it('eq_same', () => assertCel("duration('123s') == duration('123s')", true))
    it('eq_diff', () => assertCel("duration('60s') == duration('3600s')", false))
    it('neq_same', () => assertCel("duration('604800s') != duration('604800s')", false))
    it('neq_diff', () => assertCel("duration('86400s') != duration('86164s')", true))
  })

  describe('timestamp_arithmetic', () => {
    it('add_duration_to_time', () => assertCel("timestamp('2009-02-13T23:00:00Z') + duration('240s') == timestamp('2009-02-13T23:04:00Z')", true))
    it('add_time_to_duration', () => assertCel("duration('120s') + timestamp('2009-02-13T23:01:00Z') == timestamp('2009-02-13T23:03:00Z')", true))
    it('add_duration_to_duration', () => assertCel("duration('600s') + duration('50s') == duration('650s')", true))
    it.skip('add_time_to_duration_nanos_negative - nanosecond precision not supported', () => assertCel("timestamp('0001-01-01T00:00:01.000000001Z') + duration('-999999999ns') == timestamp('0001-01-01T00:00:00.000000002Z')", true))
    it.skip('add_time_to_duration_nanos_positive - nanosecond precision not supported', () => assertCel("timestamp('0001-01-01T00:00:01.999999999Z') + duration('999999999ns') == timestamp('0001-01-01T00:00:02.999999998Z')", true))
    it('subtract_duration_from_time', () => assertCel("timestamp('2009-02-13T23:10:00Z') - duration('600s') == timestamp('2009-02-13T23:00:00Z')", true))
    it('subtract_time_from_time', () => assertCel("timestamp('2009-02-13T23:31:00Z') - timestamp('2009-02-13T23:29:00Z') == duration('120s')", true))
    it('subtract_duration_from_duration', () => assertCel("duration('900s') - duration('42s') == duration('858s')", true))
  })

  describe('comparisons', () => {
    it('leq_timestamp_true', () => assertCel("timestamp('2009-02-13T23:00:00Z') <= timestamp('2009-02-13T23:00:00Z')", true))
    it('leq_timestamp_false', () => assertCel("timestamp('2009-02-13T23:00:00Z') <= timestamp('2009-02-13T22:59:59Z')", false))
    it('leq_duration_true', () => assertCel("duration('200s') <= duration('200s')", true))
    it('leq_duration_false', () => assertCel("duration('300s') <= duration('200s')", false))
    it('less_timestamp_true', () => assertCel("timestamp('2009-02-13T23:00:00Z') < timestamp('2009-03-13T23:00:00Z')", true))
    it('less_duration_true', () => assertCel("duration('200s') < duration('300s')", true))
    it('geq_timestamp_true', () => assertCel("timestamp('2009-02-13T23:00:00Z') >= timestamp('2009-02-13T23:00:00Z')", true))
    it('geq_timestamp_false', () => assertCel("timestamp('2009-02-13T22:58:00Z') >= timestamp('2009-02-13T23:00:00Z')", false))
    it('geq_duration_true', () => assertCel("duration('200s') >= duration('200s')", true))
    it('geq_duration_false', () => assertCel("duration('120s') >= duration('200s')", false))
    it('greater_timestamp_true', () => assertCel("timestamp('2009-02-13T23:59:00Z') > timestamp('2009-02-13T23:00:00Z')", true))
    it('greater_duration_true', () => assertCel("duration('300s') > duration('200s')", true))
  })

  describe('duration_converters', () => {
    it('get_hours', () => assertCel("duration('10000s').getHours()", 2n))
    it.skip('get_milliseconds - requires proto Duration binding', () => {})
    it('get_minutes', () => assertCel("duration('3730s').getMinutes()", 62n))
    it('get_seconds', () => assertCel("duration('3730s').getSeconds()", 3730n))
  })

  describe('timestamp_range', () => {
    it.skip('from_string_under', () => assertCelError("timestamp('0000-01-01T00:00:00Z')"))
    it.skip('from_string_over', () => assertCelError("timestamp('10000-01-01T00:00:00Z')"))
    it.skip('add_duration_under', () => assertCelError("timestamp('0001-01-01T00:00:00Z') + duration('-1s')"))
    it.skip('add_duration_over', () => assertCelError("timestamp('9999-12-31T23:59:59Z') + duration('1s')"))
    it.skip('add_duration_nanos_over', () => assertCelError("timestamp('9999-12-31T23:59:59.999999999Z') + duration('1ns')"))
    it.skip('add_duration_nanos_under', () => assertCelError("timestamp('0001-01-01T00:00:00Z') + duration('-1ns')"))
    it.skip('sub_time_duration_over', () => assertCelError("timestamp('9999-12-31T23:59:59Z') - timestamp('0001-01-01T00:00:00Z')"))
    it.skip('sub_time_duration_under', () => assertCelError("timestamp('0001-01-01T00:00:00Z') - timestamp('9999-12-31T23:59:59Z')"))
  })

  describe('duration_range', () => {
    it.skip('from_string_under', () => assertCelError("duration('-320000000000s')"))
    it.skip('from_string_over', () => assertCelError("duration('320000000000s')"))
    it.skip('add_under', () => assertCelError("duration('-200000000000s') + duration('-200000000000s')"))
    it.skip('add_over', () => assertCelError("duration('200000000000s') + duration('200000000000s')"))
    it.skip('sub_under', () => assertCelError("duration('-200000000000s') - duration('200000000000s')"))
    it.skip('sub_over', () => assertCelError("duration('200000000000s') - duration('-200000000000s')"))
  })
})

// ============================================================================
// fields.textproto
// ============================================================================
describe('fields', () => {
  describe('map_fields', () => {
    it('map_key_int64', () => assertCel('{0:1,2:2,5:true}[5]', true))
    it('map_key_uint64', () => assertCel("{0u:1u,2u:'happy',5u:3u}[2u]", 'happy'))
    it('map_key_string', () => assertCel("{'name':100u}['name']", 100n))
    it('map_key_bool', () => assertCel('{true:5}[true]', 5n))
    it('map_key_mixed_type', () => assertCel('{true:1,2:2,5u:3}[true]', 1n))
    it.skip('map_key_mixed_numbers_double_key', () => assertCel('{1u: 1.0, 2: 2.0, 3u: 3.0}[3.0]', 3.0))
    it.skip('map_key_mixed_numbers_lossy_double_key', () => assertCelError('{1u: 1.0, 2: 2.0, 3u: 3.0}[3.1]'))
    it.skip('map_key_mixed_numbers_uint_key', () => assertCel('{1u: 1.0, 2: 2.0, 3u: 3.0}[2u]', 2.0))
    it.skip('map_key_mixed_numbers_int_key', () => assertCel('{1u: 1.0, 2: 2.0, 3u: 3.0}[1]', 1.0))
    it('map_field_access', () => assertCel('x.name', 1024n, { x: { name: 1024n } }))
    it('map_no_such_key', () => assertCelError('{0:1,2:2,5:3}[1]'))
    it('map_no_such_key_or_false', () => assertCelError('dyn({0:1,2:2,5:3}[1]) || false'))
    it('map_no_such_key_or_true', () => assertCel('dyn({0:1,2:2,5:3}[1]) || true', true))
    it('map_no_such_key_and_false', () => assertCel('dyn({0:1,2:2,5:3}[1]) && false', false))
    it('map_no_such_key_and_true', () => assertCelError('dyn({0:1,2:2,5:3}[1]) && true'))
    it('map_bad_key_type', () => assertCelError("{0:1,2:2,5:3}[dyn(b'')]"))
    it('map_bad_key_type_or_false', () => assertCelError("dyn({0:1,2:2,5:3}[dyn(b'')]) || false"))
    it('map_bad_key_type_or_true', () => assertCel("dyn({0:1,2:2,5:3}[dyn(b'')]) || true", true))
    it('map_bad_key_type_and_false', () => assertCel("dyn({0:1,2:2,5:3}[dyn(b'')]) && false", false))
    it('map_bad_key_type_and_true', () => assertCelError("dyn({0:1,2:2,5:3}[dyn(b'')]) && true"))
    it('map_field_select_no_such_key', () => assertCelError('x.name', { x: { holiday: 'field' } }))
    it('map_field_select_no_such_key_or_false', () => assertCelError('dyn(x.name) || false', { x: { holiday: 'field' } }))
    it('map_field_select_no_such_key_or_true', () => assertCel('dyn(x.name) || true', true, { x: { holiday: 'field' } }))
    it('map_field_select_no_such_key_and_false', () => assertCel('dyn(x.name) && false', false, { x: { holiday: 'field' } }))
    it('map_field_select_no_such_key_and_true', () => assertCelError('dyn(x.name) && true', { x: { holiday: 'field' } }))
    it('map_value_null', () => assertCel('{true:null}[true]', null))
    it('map_value_bool', () => assertCel('{27:false}[27]', false))
    it('map_value_string', () => assertCel("{'n':'x'}['n']", 'x'))
    it('map_value_float', () => assertCel('{3:15.15}[3]', 15.15))
    it('map_value_uint64', () => assertCel('{0u:1u,2u:2u,5u:3u}[0u]', 1n))
    it('map_value_int64', () => assertCel('{true:1,false:2}[true]', 1n))
    it('map_value_bytes', () => assertCel("{0:b''}[0]", new Uint8Array([])))
    it('map_value_list', () => assertCel('{0u:[1]}[0u]', [1n]))
    it('map_value_map', () => assertCel("{'map': {'k': 'v'}}['map']", new Map([['k', 'v']])))
    it('map_value_mix_type', () => assertCel("{'map': {'k': 'v'}, 'list': [1]}['map']", new Map([['k', 'v']])))
  })

  describe('map_has', () => {
    it('has', () => assertCel("has({'a': 1, 'b': 2}.a)", true))
    it('has_not', () => assertCel("has({'a': 1, 'b': 2}.c)", false))
    it('has_empty', () => assertCel('has({}.a)', false))
  })

  describe('quoted_map_fields', () => {
    it.skip('field_access_slash', () => assertCel("{'/api/v1': true, '/api/v2': false}.`/api/v1`", true))
    it.skip('field_access_dash', () => assertCel("{'content-type': 'application/json', 'content-length': 145}.`content-type` == 'application/json'", true))
    it.skip('field_access_dot', () => assertCel("{'foo.txt': 32, 'bar.csv': 1024}.`foo.txt`", 32n))
    it.skip('has_field_slash', () => assertCel("has({'/api/v1': true, '/api/v2': false}.`/api/v3`)", false))
    it.skip('has_field_dash', () => assertCel("has({'content-type': 'application/json', 'content-length': 145}.`content-type`)", true))
    it.skip('has_field_dot', () => assertCel("has({'foo.txt': 32, 'bar.csv': 1024}.`foo.txt`)", true))
  })

  describe('qualified_identifier_resolution', () => {
    it.skip('qualified_ident', () => assertCel('a.b.c', 'yeah', { 'a.b.c': 'yeah' }))
    it.skip('map_field_select', () => assertCel('a.b.c', 'yeah', { 'a.b': { c: 'yeah' } }))
    it.skip('qualified_identifier_resolution_unchecked', () => {})
    it.skip('list_field_select_unsupported', () => {})
    it.skip('int64_field_select_unsupported', () => {})
    it.skip('ident_with_longest_prefix_check', () => {})
    it.skip('map_key_float', () => assertCelError('{3.3:15.15, 1.0: 5}[1.0]'))
    it.skip('map_key_null', () => assertCelError('{null:false}[null]'))
    it.skip('map_value_repeat_key', () => assertCelError('{true:1,false:2,true:3}[true]'))
    it.skip('map_value_repeat_key_heterogeneous', () => assertCelError('{0: 1, 0u: 2}[0.0]'))
  })

  describe('in', () => {
    it('empty', () => assertCel('7 in {}', false))
    it('singleton', () => assertCel('true in {true: 1}', true))
    it('present', () => assertCel("'George' in {'John': 'smart', 'Paul': 'cute', 'George': 'quiet', 'Ringo': 'funny'}", true))
    it('absent', () => assertCel("'spider' in {'ant': 6, 'fly': 6, 'centipede': 100}", false))
    it.skip('mixed_numbers_and_keys_present', () => assertCel('3.0 in {1: 1, 2: 2, 3u: 3} && 2u in {1u: 1, 2: 2} && 1 in {1u: 1, 2: 2}', true))
    it.skip('mixed_numbers_and_keys_absent', () => assertCel('3.1 in {1: 1, 2: 2, 3u: 3}', false))
  })
})

// ============================================================================
// string_ext.textproto
// ============================================================================
describe('string_ext', () => {
  describe('char_at', () => {
    it('middle_index', () => assertCel("'tacocat'.charAt(3)", 'o'))
    it('end_index', () => assertCel("'tacocat'.charAt(7)", ''))
    it('multiple', () => assertCel("'\u00a9\u03b1T'.charAt(0) == '\u00a9' && '\u00a9\u03b1T'.charAt(1) == '\u03b1' && '\u00a9\u03b1T'.charAt(2) == 'T'", true))
  })

  describe('index_of', () => {
    it.skip('empty_index', () => assertCel("'tacocat'.indexOf('')", 0n))
    it.skip('string_index', () => assertCel("'tacocat'.indexOf('ac')", 1n))
    it.skip('nomatch', () => assertCel("'tacocat'.indexOf('none') == -1", true))
    it.skip('empty_index_offset', () => assertCel("'tacocat'.indexOf('', 3) == 3", true))
    it.skip('char_index', () => assertCel("'tacocat'.indexOf('a', 3) == 5", true))
    it.skip('string_index_offset', () => assertCel("'tacocat'.indexOf('at', 3) == 5", true))
  })

  describe('last_index_of', () => {
    it('empty_string', () => assertCel("''.lastIndexOf('@@') == -1", true))
    it('empty_argument', () => assertCel("'tacocat'.lastIndexOf('') == 7", true))
    it('string', () => assertCel("'tacocat'.lastIndexOf('at') == 5", true))
    it('string_nomatch', () => assertCel("'tacocat'.lastIndexOf('none') == -1", true))
  })

  describe('ascii_casing', () => {
    it('lowerascii', () => assertCel("'TacoCat'.lowerAscii() == 'tacocat'", true))
    it('upperascii', () => assertCel("'tacoCat'.upperAscii() == 'TACOCAT'", true))
  })

  describe('replace', () => {
    it.skip('no_placeholder', () => assertCel("'12 days 12 hours'.replace('{0}', '2') == '12 days 12 hours'", true))
    it.skip('basic', () => assertCel("'{0} days {0} hours'.replace('{0}', '2') == '2 days 2 hours'", true))
    it.skip('chained', () => assertCel("'{0} days {0} hours'.replace('{0}', '2', 1).replace('{0}', '23') == '2 days 23 hours'", true))
  })

  describe('split', () => {
    it.skip('empty', () => assertCel("'hello world'.split(' ') == ['hello', 'world']", true))
    it.skip('zero_limit', () => assertCel("'hello world events!'.split(' ', 0) == []", true))
    it.skip('one_limit', () => assertCel("'hello world events!'.split(' ', 1) == ['hello world events!']", true))
  })

  describe('substring', () => {
    it.skip('start', () => assertCel("'tacocat'.substring(4) == 'cat'", true))
    it.skip('start_and_end', () => assertCel("'tacocat'.substring(0, 4) == 'taco'", true))
  })

  describe('trim', () => {
    it.skip('blank_spaces_escaped_chars', () => assertCel("' \\f\\n\\r\\t\\vtext  '.trim() == 'text'", true))
  })

  describe('join', () => {
    it('empty_separator', () => assertCel("['x', 'y'].join() == 'xy'", true))
    it('dash_separator', () => assertCel("['x', 'y'].join('-') == 'x-y'", true))
  })

  describe('quote', () => {
    it('verbatim', () => assertCel('strings.quote("verbatim") == "\\"verbatim\\""', true))
    it('empty_quote', () => assertCel('strings.quote("")', '""'))
  })

  describe('format', () => {
    it.skip('no_op', () => assertCel('"no substitution".format([])', 'no substitution'))
    it.skip('mid_string_substitution', () => assertCel('"str is %s and some more".format(["filler"])', 'str is filler and some more'))
    it.skip('percent_escaping', () => assertCel('"%%  and also %%".format([])', '%  and also %'))
    it.skip('multiple_substitutions', () => assertCel('"%d %d %d, %s %s %s, %d %d %d, %s %s %s".format([1, 2, 3, "A", "B", "C", 4, 5, 6, "D", "E", "F"])', '1 2 3, A B C, 4 5 6, D E F'))
  })

  describe('format_errors', () => {
    it.skip('unrecognized formatting clause', () => assertCelError('"%a".format([1])'))
    it.skip('out of bounds arg index', () => assertCelError('"%d %d %d".format([0, 1])'))
  })

  describe('value_errors', () => {
    it('charat_out_of_range', () => assertCelError("'tacocat'.charAt(30) == ''"))
    it.skip('substring_out_of_range', () => assertCelError("'tacocat'.substring(40) == 'cat'"))
  })

  describe('type_errors', () => {
    it('charat_invalid_type', () => assertCelError("42.charAt(2) == ''"))
    it.skip('split_invalid_type', () => assertCelError("42.split('2') == ['4']"))
  })
})

// ============================================================================
// math_ext.textproto
// ============================================================================
describe('math_ext', () => {
  describe('greatest_int_result', () => {
    it('unary_negative', () => assertCel('math.greatest(-5)', -5n))
    it('unary_positive', () => assertCel('math.greatest(5)', 5n))
    it('binary_same_args', () => assertCel('math.greatest(1, 1)', 1n))
    it('binary_first_arg_greater', () => assertCel('math.greatest(3, -3)', 3n))
    it('binary_second_arg_greater', () => assertCel('math.greatest(-7, 5)', 5n))
  })

  describe('greatest_double_result', () => {
    it('unary_negative', () => assertCel('math.greatest(-5.0)', -5.0))
    it('unary_positive', () => assertCel('math.greatest(5.0)', 5.0))
    it('binary_same_args', () => assertCel('math.greatest(1.0, 1.0)', 1.0))
    it('binary_first_arg_greater', () => assertCel('math.greatest(5.0, -7.0)', 5.0))
  })

  describe('greatest_uint_result', () => {
    it('unary', () => assertCel('math.greatest(5u)', 5n))
    it('binary_same_args', () => assertCel('math.greatest(1u, 1u)', 1n))
  })

  describe('least_int_result', () => {
    it('unary_negative', () => assertCel('math.least(-5)', -5n))
    it('unary_positive', () => assertCel('math.least(5)', 5n))
    it('binary_same_args', () => assertCel('math.least(1, 1)', 1n))
    it('binary_first_arg_least', () => assertCel('math.least(-3, 3)', -3n))
    it('binary_second_arg_least', () => assertCel('math.least(5, -7)', -7n))
  })

  describe('least_double_result', () => {
    it('unary_negative', () => assertCel('math.least(-5.5)', -5.5))
    it('unary_positive', () => assertCel('math.least(5.5)', 5.5))
    it('binary_same_args', () => assertCel('math.least(1.5, 1.5)', 1.5))
  })

  describe('least_uint_result', () => {
    it('unary', () => assertCel('math.least(5u)', 5n))
    it('binary_same_args', () => assertCel('math.least(1u, 1u)', 1n))
  })

  describe('ceil', () => {
    it.skip('negative', () => assertCel('math.ceil(-1.2)', -1.0))
    it.skip('positive', () => assertCel('math.ceil(1.2)', 2.0))
    it('dyn_error', () => assertCelError('math.ceil(dyn(1))'))
  })

  describe('floor', () => {
    it.skip('negative', () => assertCel('math.floor(-1.2)', -2.0))
    it.skip('positive', () => assertCel('math.floor(1.2)', 1.0))
    it('dyn_error', () => assertCelError('math.floor(dyn(1))'))
  })

  describe('round', () => {
    it.skip('negative_down', () => assertCel('math.round(-1.6)', -2.0))
    it.skip('negative_up', () => assertCel('math.round(-1.4)', -1.0))
    it.skip('positive_up', () => assertCel('math.round(1.5)', 2.0))
    it('dyn_error', () => assertCelError('math.round(dyn(1))'))
  })

  describe('trunc', () => {
    it.skip('negative', () => assertCel('math.trunc(-1.2)', -1.0))
    it.skip('positive', () => assertCel('math.trunc(1.2)', 1.0))
    it('dyn_error', () => assertCelError('math.trunc(dyn(1))'))
  })

  describe('abs', () => {
    it.skip('uint', () => assertCel('math.abs(1u)', 1n))
    it.skip('positive_int', () => assertCel('math.abs(1)', 1n))
    it.skip('negative_int', () => assertCel('math.abs(-11)', 11n))
    it.skip('positive_double', () => assertCel('math.abs(1.5)', 1.5))
    it.skip('negative_double', () => assertCel('math.abs(-11.5)', 11.5))
    it.skip('int_overflow', () => assertCelError('math.abs(-9223372036854775808)'))
  })

  describe('sign', () => {
    it.skip('positive_uint', () => assertCel('math.sign(100u)', 1n))
    it.skip('zero_uint', () => assertCel('math.sign(0u)', 0n))
    it.skip('positive_int', () => assertCel('math.sign(100)', 1n))
    it.skip('negative_int', () => assertCel('math.sign(-11)', -1n))
    it.skip('zero_int', () => assertCel('math.sign(0)', 0n))
    it.skip('positive_double', () => assertCel('math.sign(100.5)', 1.0))
    it.skip('negative_double', () => assertCel('math.sign(-32.0)', -1.0))
    it.skip('zero_double', () => assertCel('math.sign(0.0)', 0.0))
    it('dyn_error', () => assertCelError('math.sign(dyn(true))'))
  })

  describe('isNaN', () => {
    it.skip('true', () => assertCel('math.isNaN(0.0/0.0)', true))
    it.skip('false', () => assertCel('!math.isNaN(1.0/0.0)', true))
    it('dyn_error', () => assertCelError('math.isNaN(dyn(true))'))
  })

  describe('isInf', () => {
    it.skip('true', () => assertCel('math.isInf(1.0/0.0)', true))
    it.skip('false', () => assertCel('!math.isInf(0.0/0.0)', true))
    it('dyn_error', () => assertCelError('math.isInf(dyn(true))'))
  })

  describe('isFinite', () => {
    it.skip('true', () => assertCel('math.isFinite(1.0/1.5)', true))
    it.skip('false_nan', () => assertCel('!math.isFinite(0.0/0.0)', true))
    it.skip('false_inf', () => assertCel('!math.isFinite(-1.0/0.0)', true))
    it('dyn_error', () => assertCelError('math.isFinite(dyn(true))'))
  })

  describe('bit_and', () => {
    it.skip('int_int_non_intersect', () => assertCel('math.bitAnd(1, 2)', 0n))
    it.skip('int_int_intersect', () => assertCel('math.bitAnd(1, 3)', 1n))
    it.skip('uint_uint_non_intersect', () => assertCel('math.bitAnd(1u, 2u)', 0n))
    it.skip('uint_uint_intersect', () => assertCel('math.bitAnd(1u, 3u)', 1n))
  })

  describe('bit_or', () => {
    it.skip('int_int_positive', () => assertCel('math.bitOr(1, 2)', 3n))
    it.skip('uint_uint', () => assertCel('math.bitOr(1u, 4u)', 5n))
  })

  describe('bit_xor', () => {
    it.skip('int_int_positive', () => assertCel('math.bitXor(1, 3)', 2n))
    it.skip('uint_uint', () => assertCel('math.bitXor(1u, 3u)', 2n))
  })

  describe('bit_not', () => {
    it.skip('int_positive', () => assertCel('math.bitNot(1)', -2n))
    it.skip('int_negative', () => assertCel('math.bitNot(-1)', 0n))
    it.skip('uint_positive', () => assertCel('math.bitNot(1u)', 18446744073709551614n))
  })

  describe('bit_shift_left', () => {
    it.skip('int', () => assertCel('math.bitShiftLeft(1, 2)', 4n))
    it.skip('uint', () => assertCel('math.bitShiftLeft(1u, 2)', 4n))
  })

  describe('bit_shift_right', () => {
    it.skip('int', () => assertCel('math.bitShiftRight(1024, 2)', 256n))
    it.skip('uint', () => assertCel('math.bitShiftRight(1024u, 2)', 256n))
  })
})

// ============================================================================
// bindings_ext.textproto
// ============================================================================
describe('bindings_ext', () => {
  describe('bind', () => {
    it.skip('boolean_literal', () => assertCel('cel.bind(t, true, t)', true))
    it.skip('string_concat', () => assertCel('cel.bind(msg, "hello", msg + msg + msg)', 'hellohellohello'))
    it.skip('bind_nested', () => assertCel('cel.bind(t1, true, cel.bind(t2, true, t1 && t2))', true))
    it.skip('macro_exists', () => assertCel('cel.bind(valid_elems, [1, 2, 3], [3, 4, 5].exists(e, e in valid_elems))', true))
    it.skip('macro_not_exists', () => assertCel('cel.bind(valid_elems, [1, 2, 3], ![4, 5].exists(e, e in valid_elems))', true))
    it.skip('shadowing', () => assertCel('cel.bind(x, 0, x == 0)', true, { x: 1n }))
    it.skip('shadowing_namespace_resolution', () => {})
    it.skip('shadowing_namespace_resolution_selector', () => {})
  })
})

// ============================================================================
// optionals.textproto
// ============================================================================
describe('optionals', () => {
  describe('optionals', () => {
    it.skip('null', () => assertCel('optional.of(null).hasValue()', true))
    it.skip('null_non_zero_value', () => assertCel('optional.ofNonZeroValue(null).hasValue()', false))
    it.skip('none_or_none_or_value', () => assertCel('optional.none().or(optional.none()).orValue(42)', 42n))
    it.skip('none_optMap_hasValue', () => assertCel('optional.none().optMap(y, y + 1).hasValue()', false))
    it.skip('empty_map_optFlatMap_hasValue', () => assertCel('{}.?key.optFlatMap(k, k.?subkey).hasValue()', false))
    it.skip('map_empty_submap_optFlatMap_hasValue', () => assertCel("{'key': {}}.?key.optFlatMap(k, k.?subkey).hasValue()", false))
    it('map_null_entry_hasValue', () => assertCel("{'null_key': dyn(null)}.?null_key.hasValue()", true))
    it('map_null_entry_no_such_key', () => assertCelError("{'null_key': dyn(null)}.?null_key.invalid.hasValue()"))
    it('map_absent_key_absent_field_none', () => assertCel('{true: dyn(0)}[?false].absent.hasValue()', false))
    it('map_present_key_invalid_field', () => assertCelError('{true: dyn(0)}[?true].absent.hasValue()'))
    it.skip('map_undefined_entry_hasValue', () => assertCel('{}.?null_key.invalid.hasValue()', false))
    it.skip('map_submap_subkey_optFlatMap_value', () => assertCel("{'key': {'subkey': 'subvalue'}}.?key.optFlatMap(k, k.?subkey).value()", 'subvalue'))
    it.skip('map_submap_optFlatMap_value', () => assertCel("{'key': {'subkey': ''}}.?key.optFlatMap(k, k.?subkey).value()", ''))
    it.skip('map_optindex_optFlatMap_optional_ofNonZeroValue_hasValue', () => assertCel("{'key': {'subkey': ''}}.?key.optFlatMap(k, optional.ofNonZeroValue(k.subkey)).hasValue()", false))
    it.skip('optional_of_optMap_value', () => assertCel('optional.of(42).optMap(y, y + 1).value()', 43n))
    it.skip('optional_ofNonZeroValue_or_optional_value', () => assertCel('optional.ofNonZeroValue(42).or(optional.of(20)).value() == 42', true))
    it.skip('ternary_optional_hasValue', () => assertCel('(has({}.x) ? optional.of({}.x) : optional.none()).hasValue()', false))
    it.skip('map_optindex_hasValue', () => assertCel('{}.?x.hasValue()', false))
    it.skip('has_map_optindex', () => assertCel('has({}.?x.y)', false))
    it.skip('has_map_optindex_field', () => assertCel("has({'x': {'y': 'z'}}.?x.y)", true))
    it.skip('type', () => assertCel('type(optional.none()) == optional_type', true))
    it.skip('optional_chaining_1', () => assertCel("optional.ofNonZeroValue('').or(optional.of({'c': {'dashed-index': 'goodbye'}}.c['dashed-index'])).orValue('default value')", 'goodbye'))
    it.skip('optional_chaining_2', () => assertCel("{'c': {'dashed-index': 'goodbye'}}.c[?'dashed-index'].orValue('default value')", 'goodbye'))
    it.skip('optional_chaining_3', () => assertCel("{'c': {}}.c[?'missing-index'].orValue('default value')", 'default value'))
    it.skip('optional_chaining_4', () => assertCel("optional.of({'c': {'index': 'goodbye'}}).c.index.orValue('default value')", 'goodbye'))
    it.skip('optional_chaining_5', () => assertCel("optional.of({'c': {}}).c.missing.or(optional.none()[0]).orValue('default value')", 'default value'))
    it.skip('optional_chaining_6', () => assertCel("optional.of({'c': {}}).c.missing.or(optional.of(['list-value'])[0]).orValue('default value')", 'list-value'))
    it.skip('optional_chaining_7', () => assertCel("optional.of({'c': {'index': 'goodbye'}}).c['index'].orValue('default value')", 'goodbye'))
    it.skip('optional_chaining_8', () => assertCel("optional.of({'c': {}}).c['missing'].orValue('default value')", 'default value'))
    it.skip('optional_chaining_9', () => assertCel("has(optional.of({'c': {'entry': 'hello world'}}).c) && !has(optional.of({'c': {'entry': 'hello world'}}).c.missing)", true))
    it.skip('optional_chaining_10', () => assertCelError("optional.ofNonZeroValue({'c': {'dashed-index': 'goodbye'}}.a.z).orValue({'c': {'dashed-index': 'goodbye'}}.c['dashed-index'])"))
    it.skip('optional_chaining_11', () => assertCel("{'c': {'dashed-index': 'goodbye'}}.?c.missing.or({'c': {'dashed-index': 'goodbye'}}.?c['dashed-index']).orValue('').size()", 7n))
    it.skip('optional_chaining_12 - complex map', () => {})
    it.skip('optional_chaining_13 - complex map', () => {})
    it.skip('optional_chaining_14', () => assertCel('[?{}.?c, ?optional.of(42), ?optional.none()]', [42n]))
    it('optional_chaining_15', () => assertCel("[?optional.ofNonZeroValue({'c': []}.?c.orValue(dyn({})))]", []))
    it.skip('optional_chaining_16', () => assertCel("optional.ofNonZeroValue({?'nested_map': optional.ofNonZeroValue({?'map': optional.of({}).?c})}).hasValue()", false))
    it.skip('has_optional_ofNonZeroValue_struct - proto', () => {})
    it.skip('optional_ofNonZeroValue_struct - proto', () => {})
    it.skip('struct_map_optindex_field - proto', () => {})
    it.skip('struct_optional_ofNonZeroValue - proto', () => {})
    it.skip('struct_map_optindex_field_nested - proto', () => {})
    it.skip('struct_list_optindex_field - proto', () => {})
    it.skip('optional_empty_map_optindex_hasValue', () => assertCel('optional.of({}).?c.hasValue()', false))
    it.skip('empty_struct_optindex_hasValue - proto', () => {})
    it.skip('optional_empty_struct_optindex_hasValue - proto', () => {})
    it.skip('optional_none_optselect_hasValue', () => assertCel('optional.none().?repeated_string.hasValue()', false))
    it.skip('struct_optindex_value - proto', () => {})
    it.skip('optional_struct_optindex_value - proto', () => {})
    it.skip('optional_struct_optindex_index_value - proto', () => {})
    it.skip('empty_list_optindex_hasValue', () => assertCel('[][?0].hasValue()', false))
    it.skip('optional_empty_list_optindex_hasValue', () => assertCel('optional.of([])[?0].hasValue()', false))
    it.skip('optional_none_optindex_hasValue', () => assertCel('optional.none()[?0].hasValue()', false))
    it.skip('list_optindex_value', () => assertCel("['foo'][?0].value()", 'foo'))
    it.skip('optional_list_optindex_value', () => assertCel("optional.of(['foo'])[?0].value()", 'foo'))
    it.skip('map_key_mixed_type_optindex_value', () => assertCel('{true: 1, 2: 2, 5u: 3}[?true].value()', 1n))
    it.skip('optional_eq_none_none', () => assertCel('optional.none() == optional.none()', true))
    it.skip('optional_eq_none_int', () => assertCel('optional.none() == optional.of(1)', false))
    it.skip('optional_eq_int_none', () => assertCel('optional.of(1) == optional.none()', false))
    it.skip('optional_eq_int_int', () => assertCel('optional.of(1) == optional.of(1)', true))
    it.skip('optional_ne_none_none', () => assertCel('optional.none() != optional.none()', false))
    it.skip('optional_ne_none_int', () => assertCel('optional.none() != optional.of(1)', true))
    it.skip('optional_ne_int_none', () => assertCel('optional.of(1) != optional.none()', true))
    it.skip('optional_ne_int_int', () => assertCel('optional.of(1) != optional.of(1)', false))
    it.skip('map_optional_has', () => assertCel("has({'foo': optional.none()}.foo)", true))
    it.skip('map_optional_select_has', () => assertCel("has({'foo': optional.none()}.foo.bar)", false))
    it.skip('map_optional_entry_has', () => assertCel("has({?'foo': optional.none()}.foo)", false))
  })
})
