import { describe, it } from 'node:test'
import { assertCel, assertCelError } from '../helpers.js'

describe('comparisons', () => {
  describe('equality', () => {
    it('1 == 1', () => assertCel('1 == 1', true))
    it('1 == 2', () => assertCel('1 == 2', false))
    it('"hello" == "hello"', () => assertCel('"hello" == "hello"', true))
    it('"hello" == "world"', () => assertCel('"hello" == "world"', false))
    it('true == true', () => assertCel('true == true', true))
    it('true == false', () => assertCel('true == false', false))
    it('null == null', () => assertCel('null == null', true))
  })

  describe('inequality', () => {
    it('1 != 2', () => assertCel('1 != 2', true))
    it('1 != 1', () => assertCel('1 != 1', false))
    it('"a" != "b"', () => assertCel('"a" != "b"', true))
  })

  describe('less than', () => {
    it('1 < 2', () => assertCel('1 < 2', true))
    it('2 < 1', () => assertCel('2 < 1', false))
    it('2 < 2', () => assertCel('2 < 2', false))
    it('-5 < -3', () => assertCel('-5 < -3', true))
    it('-3 < -5', () => assertCel('-3 < -5', false))
    it('-1 < 0', () => assertCel('-1 < 0', true))
    it('0 < -1', () => assertCel('0 < -1', false))
    it('false < true', () => assertCel('false < true', true))
    it('true < false', () => assertCel('true < false', false))
    it('true < true', () => assertCel('true < true', false))
    it('false < false', () => assertCel('false < false', false))
    it('"a" < "b"', () => assertCel('"a" < "b"', true))
    it('"b" < "a"', () => assertCel('"b" < "a"', false))
    it('"hello" < "hello"', () => assertCel('"hello" < "hello"', false))
    it('"abc" < "abcd"', () => assertCel('"abc" < "abcd"', true))
    it('"" < "a"', () => assertCel('"" < "a"', true))
    it('"a" < ""', () => assertCel('"a" < ""', false))
    it('"A" < "a"', () => assertCel('"A" < "a"', true))
    it('1.0 < 2.0', () => assertCel('1.0 < 2.0', true))
    it('2.0 < 2.0', () => assertCel('2.0 < 2.0', false))
    it('3.0 < 2.0', () => assertCel('3.0 < 2.0', false))
    it('-5.5 < -3.3', () => assertCel('-5.5 < -3.3', true))
    it('1.1 < 1.2', () => assertCel('1.1 < 1.2', true))
    it('0.001 < 0.002', () => assertCel('0.001 < 0.002', true))
    it('uint(1) < uint(2)', () => assertCel('uint(1) < uint(2)', true))
    it('uint(2) < uint(2)', () => assertCel('uint(2) < uint(2)', false))
    it('uint(3) < uint(2)', () => assertCel('uint(3) < uint(2)', false))
  })

  describe('less than or equal', () => {
    it('1 <= 1', () => assertCel('1 <= 1', true))
    it('1 <= 2', () => assertCel('1 <= 2', true))
    it('2 <= 1', () => assertCel('2 <= 1', false))
    it('-5 <= -3', () => assertCel('-5 <= -3', true))
    it('-3 <= -3', () => assertCel('-3 <= -3', true))
    it('true <= true', () => assertCel('true <= true', true))
    it('false <= false', () => assertCel('false <= false', true))
    it('false <= true', () => assertCel('false <= true', true))
    it('true <= false', () => assertCel('true <= false', false))
    it('"a" <= "b"', () => assertCel('"a" <= "b"', true))
    it('"hello" <= "hello"', () => assertCel('"hello" <= "hello"', true))
    it('"b" <= "a"', () => assertCel('"b" <= "a"', false))
    it('"" <= "a"', () => assertCel('"" <= "a"', true))
    it('"" <= ""', () => assertCel('"" <= ""', true))
    it('1.0 <= 2.0', () => assertCel('1.0 <= 2.0', true))
    it('2.0 <= 2.0', () => assertCel('2.0 <= 2.0', true))
    it('3.0 <= 2.0', () => assertCel('3.0 <= 2.0', false))
    it('uint(1) <= uint(2)', () => assertCel('uint(1) <= uint(2)', true))
    it('uint(2) <= uint(2)', () => assertCel('uint(2) <= uint(2)', true))
    it('uint(3) <= uint(2)', () => assertCel('uint(3) <= uint(2)', false))
  })

  describe('greater than', () => {
    it('2 > 1', () => assertCel('2 > 1', true))
    it('1 > 2', () => assertCel('1 > 2', false))
    it('2 > 2', () => assertCel('2 > 2', false))
    it('-3 > -5', () => assertCel('-3 > -5', true))
    it('0 > -1', () => assertCel('0 > -1', true))
    it('true > false', () => assertCel('true > false', true))
    it('false > true', () => assertCel('false > true', false))
    it('true > true', () => assertCel('true > true', false))
    it('"b" > "a"', () => assertCel('"b" > "a"', true))
    it('"a" > "b"', () => assertCel('"a" > "b"', false))
    it('"hello" > "hello"', () => assertCel('"hello" > "hello"', false))
    it('"abcd" > "abc"', () => assertCel('"abcd" > "abc"', true))
    it('"a" > ""', () => assertCel('"a" > ""', true))
    it('"" > ""', () => assertCel('"" > ""', false))
    it('2.0 > 1.0', () => assertCel('2.0 > 1.0', true))
    it('2.0 > 2.0', () => assertCel('2.0 > 2.0', false))
    it('1.0 > 2.0', () => assertCel('1.0 > 2.0', false))
    it('1.2 > 1.1', () => assertCel('1.2 > 1.1', true))
    it('uint(2) > uint(1)', () => assertCel('uint(2) > uint(1)', true))
    it('uint(2) > uint(2)', () => assertCel('uint(2) > uint(2)', false))
    it('uint(1) > uint(2)', () => assertCel('uint(1) > uint(2)', false))
  })

  describe('greater than or equal', () => {
    it('1 >= 1', () => assertCel('1 >= 1', true))
    it('2 >= 1', () => assertCel('2 >= 1', true))
    it('1 >= 2', () => assertCel('1 >= 2', false))
    it('-3 >= -5', () => assertCel('-3 >= -5', true))
    it('-3 >= -3', () => assertCel('-3 >= -3', true))
    it('true >= true', () => assertCel('true >= true', true))
    it('true >= false', () => assertCel('true >= false', true))
    it('false >= true', () => assertCel('false >= true', false))
    it('"b" >= "a"', () => assertCel('"b" >= "a"', true))
    it('"hello" >= "hello"', () => assertCel('"hello" >= "hello"', true))
    it('"a" >= "b"', () => assertCel('"a" >= "b"', false))
    it('"a" >= ""', () => assertCel('"a" >= ""', true))
    it('"" >= ""', () => assertCel('"" >= ""', true))
    it('2.0 >= 1.0', () => assertCel('2.0 >= 1.0', true))
    it('2.0 >= 2.0', () => assertCel('2.0 >= 2.0', true))
    it('1.0 >= 2.0', () => assertCel('1.0 >= 2.0', false))
    it('uint(2) >= uint(1)', () => assertCel('uint(2) >= uint(1)', true))
    it('uint(2) >= uint(2)', () => assertCel('uint(2) >= uint(2)', true))
    it('uint(1) >= uint(2)', () => assertCel('uint(1) >= uint(2)', false))
  })

  describe('type mismatches', () => {
    it('should reject incompatible types', () => {
      assertCelError('"a" < 1')
      assertCelError('1 < "a"')
      assertCelError('true < 1')
      assertCelError('true < "a"')
    })
  })
})
